### ISSUE TITLE
Kelas Docker untuk tim Infra 

### ISSUE THREAD

**Issue by samsulmaarif** [BlankOn/Verbeek#104]
- Pemateri Pak Estu Fardani @tuanpembual 
- Tempat berkumpul: https://meet.google.com/awu-apxq-cfg
- Waktu : 8 November 2020, 20:00 s.d. selesai
- Salindia: -
- Agenda: 
  - perkenalan podman
  - `alias docker=podman`
  - praktek

**Comment by samsulmaarif** [comment]
Diundur nanti malam, Selasa, 10 November 2020, pukul berapa? cc @kudaliar032 @misskecupbung @tuanpembual

**Comment by kudaliar032** [comment]
Saya menyesuaikan pak @samsulmaarif

**Comment by samsulmaarif** [comment]
@samsulmaarif bapak ibu pendekar yang mau ikut silakan, kelasnya malam ini mau dimulai

**Comment by herpiko** [comment]
Ini sudah bukan ya? Bisa ditutup berti? @samsulmaarif

**Comment by samsulmaarif** [comment]
pak @tuanpembual sepertinya akan membuka kelas lanjutan yang boleh direkam. Apakah bikin tiket baru atau cukup pake tiket ini pak @herpiko ?

**Comment by herpiko** [comment]
@samsulmaarif Tiket baru, kecuali ini memang `tidak selesai`.

**Comment by samsulmaarif** [comment]
@herpiko Siap pak
