### ISSUE TITLE
Kelas GPG

### ISSUE THREAD

**Issue by antosamalona** [BlankOn/Verbeek#107]
Perlu buat kelas khusus untuk GPG karena termasuk fundamental

**Comment by herpiko** [comment]
Skup:
- Manajemen kunci di lokal:
  - gen
  - import
  - export
  - hapus
- Tanda tangan:
  - Tanda tangan
  - Verifikasi
- Advances:
  - TTD di commit
  - GPG di pesan surel

**Comment by herpiko** [comment]
Tiket ini saya tutup, materinya jadi satu di https://github.com/BlankOn/Verbeek/issues/119
