### ISSUE TITLE
Riset Jekyll

### ISSUE THREAD

**Issue by tuanpembual** [BlankOn/Verbeek#108]
- [x] Install Jekyll
- [x] Deploy Jekyll
- [x] Belajar Desain Template, base on https://github.com/openSUSE/news-o-o
- [x] Implementasi template berdasarkan warna blankon dari https://github.com/BlankOn/blankon-linux-static-web
- [x] Deploy Wajah Baru BlankOn

**Comment by herpiko** [comment]
Point keempat perlu konsultasi ke tim kesenian untuk warna palette.

**Comment by samsulmaarif** [comment]
Ini targetnya sebagai pengganti web panduan atau serambi ya pak @tuanpembual atau dua-duanya?

**Comment by tuanpembual** [comment]
ini sudah masuk taraf testing dan uji konten.

Beberapa bagian butuh poles tampilan.

**Comment by tuanpembual** [comment]
@samsulmaarif serambi bisa saya masukin ke tautan dari menu

**Comment by tuanpembual** [comment]
done.
