### ISSUE TITLE
Kolaborasi Garap Proposal

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#113]
Waktu: Selasa, 17 November 2020 19.00 WIB di Gmeet
Bahasan:
  - Proposal resmi pembaruan mesin
  - Proposal saweran jangka pendek
Output: 
- Dokumen proposal yang siap
- Template baku, berkasnya setor ke wiki.

**Comment by slamets75** [comment]
komunikasi dengan tim humas (on progress)
share drive humas untuk project verbeek sudah undang pak @herpiko & pak @tuanpembual 

untuk dokumen proposal kita sedang coba edit dari file proposal lama untuk disesuaikan dengan kebutuhan yang ada 
https://drive.google.com/file/d/1VQZ853LNNjE8iJ8g39KDMxfQkmWRUvtO/view?usp=sharing

**Comment by herpiko** [comment]
Pedoman dokumen:
- Kurangi penggunaan kosakata/frasa berbahasa inggris
- Perbarui data yang ada (tanggal, tahun, struktur, nama, dst)
- Sesuaikan kebutuhan riil.

**Comment by herpiko** [comment]
Ini sudah selesai dan narasinya juga sudah digunakan di tiket #121. Dokumen asli ada di @slamets75 .
