### ISSUE TITLE
Saweran KitaBisa

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#114]
Lewat kitabisa. Perlu,

- Copywriting dan campaign yang kuat mengenai tujuan proyek, follow up Tim Kesenian.
- Format laporan keuangan yang baku untuk dirilis secara berkala, follow up Tim Humas
- Aksi, follow up Tim Humas

**Comment by slamets75** [comment]
sedang dibawa koordinasi dengan tim humas, jika sudah akan di update kemari.

**Comment by slamets75** [comment]
Pembukaan rekening BRI baru di khususkan oleh tim humas untuk wadah donasi sponsor project pengembangan BlankOn sebelum didirikan yayasan.

**Comment by herpiko** [comment]
@slamets75 

Terkait koordinasi:
- Semua pekerjaan harus berbasis tiket. Semua input, bahan, draft pekerjaan apa pun itu ditempel ke tiket. Pertimbangan:
  - Open governance
  - Membuka peluang untuk direview oleh tim lain sebelum dibawa ke production
  - Orang lain bisa belajar dari pekerjaan yang kita lakukan
- Tim JK sekarang sudah bukan lagi tim yang cuma booting ISO terus lapor kutu. Tim JK sekarang adalah QA secara luas yang juga bisa dimintai pendapat/masukan untuk apa pun itu, termasuk review bahan campaign yang mau kita bawa ke publik.
- Terlebih karena humas adalah wajah proyek, semua hal yang akan dibawa ke publik perlu direview dengan matang. Pertimbangkan 2 poin di atas. Menerapkan 2 poin di atas bukan berarti memotong wewenang humas, tapi justru membantu humas untuk lebih baik lagi dan wewenang/keputusan akhir tetap ada di humas.

Terkait konten di kitabisa:
- Saat rapat kemarin sudah disepakati kalau kita juga harus menjelaskan ke donatur mengenai:
  - Tujuan kita ini apa? Belum ada: semua ada di narasi yang ditulis bareng kemarin:
    - Tujuan proyek: peningkatan sdm
    - Tujuan produk: bikin distribusi khusus untuk pekerja IT
  - Kenapa kita butuh bantuan? Bakal dipake buat apaan? sudah ada, tengs.
  - Apa timbal baliknya untuk mereka? Belum ada: kemarin kita tulis kita menjanjikan:
    - Laporan keuangan
    - Laporan perkembangan/kegiatan yang dipublish dalam blog resmi
- Jika ini adalah jangka pendek dan bakal ada lagi, ambil judul (dan slug url) yang masuk akal dan tidak generik.
"Misal Urunan Pengembangan Proyek BlankOn Tahap I"

**Comment by herpiko** [comment]
Dari @Cengkaruk 

Titip ini aja sih.

"Saya tergerak menggalang dana karena melihat kondisi terkini dimana tim pengembang BlankOn XII Verbeek sudah mulai berjalan namun terkendala dengan mesin dan infrastruktur sebagai oprasional mereka."

Itu perlu disesuaikan banget.

Menurut saya gini pak. Lebih baik kita atau kami, pengembang BlankOn yang menggalang dana

**Comment by herpiko** [comment]
@slamets75 

1. Tentukan mana jangka panjang mana jangka pendek, jadi lebih jelas untuk keberlanjutannya
2. Kurangi konteks personal
3. Narasi tambahkan tujuan (proyek, produk), timbal balik

**Comment by slamets75** [comment]
**Pertama**
Jangka Panjang Saweran di KitaBisa
- Kampanye proyek dan perangkat lunak terbuka

Jangka Pendek Saweran di KitaBisa
- Pengembangan, pemeliharaan dan pembiayaan infrastruktur.
- Penyelenggaraan acara-acara proyek seperti konferensi BlankOn, BlanKopdar dsb.
- Pembiayaan partisipasi proyek pada acara-acara komunitas berbasis perangkat lunak terbuka.

**Ke-2**

**Comment by herpiko** [comment]
Saweran jangka pendek pertama ada di https://github.com/BlankOn/Verbeek/issues/121.

Tiket ini saya tutup.
