### ISSUE TITLE
Lokakarya Docker untuk Umum

### ISSUE THREAD

**Issue by samsulmaarif** [BlankOn/Verbeek#116]
Melanjutkan kelas #104 yang baru membahas fundamental dan penjelasan praktek baik penggunaan Docker.

**Comment by herpiko** [comment]
@samsulmaarif @tuanpembual sudah usula/ketetapan tanggal?

**Comment by samsulmaarif** [comment]
Dari pembahasan rapat koordinator pada Sabtu, 23 Januari 2021 kemarin diusulkan:

- agar lokakarya ini dibuka untuk umum
- diumumkan melalui kanal-kanal humas yang ada jauh sebelum acara
- poster dibuatkan oleh tim kesenian untuk publikasi
- untuk menarik peserta bisa kita buatkan sertifikat bagi peserta yang mengikuti dari awal hingga akhir dan menyelesaikan tugas dari pemateri
- di tengah lokakarya kita bisa selipkan manfaat apabila peserta bergabung sebagai pengembang BlankOn (rekrutmen)
- lokakarya bisa dibuat menjadi beberapa pertemuan

Bapak @somat sepertinya bersedia menjadi koordinator untuk lokakarya ini?

Terkait tanggal pelaksanaan ada usulan Bapak/Ibu?

**Comment by somat** [comment]
Hasil obrolan dengan pak @tuanpembual :

* Loka karya daring dengan tema: "Docker Best Practice Untuk Developer"
* Nara sumber: Estu Fardani
* Tanggal: 13 Februari 2021 jam: 19:00 - 21:00
* Peserta: Umum
* Pendaftaran: s.id/ws-docker
* Ruang kelas: Google Meet

Catatan:
* _Bagi peserta yang akan mengikuti praktik selama materi berjalan, diharapkan sudah memasang Docker di laptop masing-masing._

**Comment by herpiko** [comment]
Pak @somat, ini sepertinya perlu tentukan tanggal berapa poster dan woro-woro mesti ready, jadi tim kesenian punya ancer-ancer waktu untuk garap poster.

**Comment by somat** [comment]
> Pak @somat, ini sepertinya perlu tentukan tanggal berapa poster dan woro-woro mesti ready, jadi tim kesenian punya ancer-ancer waktu untuk garap poster.

Oke pak, supaya cukup untuk woro-woco maka akan lebih baik kalau posternya sudah jadi sebelum tanggal 1 ya pak.

Untuk request dibuatkan poster caranya bagaimana ya?, apakah membuat tiket baru?

**Comment by herpiko** [comment]
@somat Boleh bikin tiket baru, boleh mensyen koordinator timkes di tiket terkait.

**Comment by somat** [comment]
Baik pak @herpiko .

Dear pak @raniaamina , mau minta tolong request poster untuk bahan pengumuman loka karya dengan detil seperti [di sini](https://github.com/BlankOn/Verbeek/issues/116#issuecomment-766370270) ya pak.

**Comment by raniaamina** [comment]
@somat Okay pak

**Comment by samsulmaarif** [comment]
Halo pak @somat, menurut Bapak terkait tiket ini perlu dijadwalkan ulang atau kita tutup saja ya pak?

**Comment by samsulmaarif** [comment]
Untuk sementara kita tutup dulu ya. Jika hendak membuka kelas tiket bisa dibuka kembali (atau buat baru).
