### ISSUE TITLE
Tambahkan tautan/menu baru di situs utama boi, bagaimana berkontribusi, arahkan ke wiki dev

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#117]
Dari wiki, diperjelas lagi arahnya. Pengembang baru kalo mengunjungi halaman ini punya arah yang jelas. Perlu digiring dalam 3 tahap:

- Memastikan memenuhi persyaratan
- Mengenalkan diri ke milis
- Mengirim pull request untuk menambahkan nama tim
- Tim pengembang akan mengundang calon pengembang ke grup diskusi.

**Comment by herpiko** [comment]
Halaman depan wiki diperpendek menjadi seperti ini:

![Screenshot from 2020-11-18 10-11-51](https://user-images.githubusercontent.com/2534060/99478184-847be280-2986-11eb-9c9e-4742b0672e81.png)

Adapun halaman "Memulai" diperbarui seperti ini.

![Screenshot from 2020-11-18 10-14-02](https://user-images.githubusercontent.com/2534060/99478350-d15fb900-2986-11eb-9d53-e7824e959f8b.png)

Jadi Memulai.md ini menjadi satu halaman yang menjelaskan semua hal untuk memulai. Sekarang yang kurang dari tiket ini adalah menambahkan tautan di situs utama blengon (https://blankonlinux.or.id/) yang mengarah ke https://github.com/BlankOn/wiki/blob/master/Memulai.md

**Comment by samsulmaarif** [comment]
Selesai di https://github.com/BlankOn/blankon.github.io/pull/1
