### ISSUE TITLE
Saweran KitaBisa.Com | Pengembangan, Pemeliharaan & Pembiayaan Infrastruktur

### ISSUE THREAD

**Issue by slamets75** [BlankOn/Verbeek#121]
Mohon bantuan diulas konten pada Saweran KitaBisa.Com | Pengembangan, Pemeliharaan & Pembiayaan Infrastruktur

https://kitabisa.com/urunanpengembanganblankon

**Comment by samsulmaarif** [comment]
Sepertinya masih ada saltik pada paragraf ke-2 

> Kami tergerak menggalang dana karena melihat kondisi terkini dimana tim pengembang BlankOn XII Verbeek sudah mulai berjalan namun terkendala dengan mesin dan infrastruktur sebagai oprasional mereka.

- "oprasional mereka" --> operasional
- ^^ menghilangkan kata "mereka" atau diganti dengan "kami"

**Comment by slamets75** [comment]
@samsulmaarif Sudah tak perbarui ✅

**Comment by FaiqAminuddin** [comment]
usul penyuntingan

Halo #OrangBaik,

Kami dari pengembang BlankOn, kami ingin menggalang dana untuk Pengembangan, >> *pengembangan*
 pemeliharaan dan pembiayaan infrastruktur.

Kami tergerak menggalang dana karena melihat kondisi terkini  
dimana >> hapus
tim pengembang BlankOn XII Verbeek 
tambahkan kata "yang" 
sudah mulai berjalan namun terkendala dengan mesin dan infrastruktur sebagai operasional kami.

Donasi yang terkumpul nantinya akan digunakan untuk;
Biaya Pemiliharaan Infrastruktur & Server. >> Biaya pemeliharaan infrastruktur dan server.

...
Tujuan Produk : Membuat distribusi khusus untuk pekerja IT.

Timbal Balik : >> Laporan
- Laporan keuangan.>> - Laporan keuangan akan 
dipublish >> dipublikasikan
dalam blog resmi.

**Comment by slamets75** [comment]
@FaiqAminuddin Terima kasih pak, tak ubah 🔄

**Comment by slamets75** [comment]
@slamets75 Pembaruan narasi sesuai buah pikir dan tulisan sang manajer rilis.

**Comment by herpiko** [comment]
Sudah dirilis, https://kitabisa.com/campaign/urunanpengembanganblankon

**Comment by slamets75** [comment]
List kanal dikirimkan info saweran
- [ ] Telegram group (BlankOn-Dev Verbeek)
- [ ] Telegram group pengguna blankon (BlankOn Linux) 
- [ ] Instagram BlankOn Linux
- [ ] Facebook BlankOn Linux
- [ ] Twitter BlankOn Linux

**Comment by herpiko** [comment]
Untuk facebook, saya nemu ada 2 nih.

- https://www.facebook.com/groups/blankonlinux
- https://www.facebook.com/blankon.linux

Yang dipelihara humas yang mana? Apakah dua-duanya?

**Comment by slamets75** [comment]
> Untuk facebook, saya nemu ada 2 nih.
> 
> * https://www.facebook.com/groups/blankonlinux
> * https://www.facebook.com/blankon.linux
> 
> Yang dipelihara humas yang mana? Apakah dua-duanya?

https://www.facebook.com/blankon.linux

yang ini pak, untuk group saya coba tanyakan di group humas dulu ya

**Comment by herpiko** [comment]
@slamets75 Siap. Kalau ternyata yang satu itu ga ada yang pegang di tim yang sekarang, mohon telusuri siapa kuncennya sampai dapat, terus ajukan permohonan transfer kepemilikan.

**Comment by slamets75** [comment]
@herpiko siap 86

**Comment by samsulmaarif** [comment]
@herpiko yang grup kuncennya ada banyak pak, sebagian besar masih aktif di Facebook, pak Estu dan Saya termasuk jadi admin di situ

**Comment by herpiko** [comment]
@samsulmaarif Oalah. Mohon semua anggota tim humas diangkat sebagai jendral di daerah terkait.

**Comment by samsulmaarif** [comment]
@herpiko sepertinya saya dan pak @senyumslamet belum berteman di Facebook pak

**Comment by herpiko** [comment]
@slamets75 Untuk milis (blankon-dev maupun blankon) sudah saya kirimkan tadi sore.

**Comment by slamets75** [comment]
Update info Saweran kitabisa.com - 21/11/2020 - 17.48

Urunan Pengembangan Proyek BlankOn
Rp 5.650.684 terkumpul dari Rp 25.000.000
9 Donasi | 27 hari lagi

**Comment by tuanpembual** [comment]
ini saya tutup, karena sudah mengudara, laporan dan berita sudah saya salin di kanal berita.

**Comment by slamets75** [comment]
Masa donasi diperpanjang sampai dengan 31 Desember 2020.

**Comment by samsulmaarif** [comment]
masa donasi sudah berakhir, tiket saya tutup.
