### ISSUE TITLE
Lokakarya Copywriting

### ISSUE THREAD

**Issue by slamets75** [BlankOn/Verbeek#122]
Kebutuhan kelas khusus untuk tim Humas.

Waktu & Pemateri bisa diusulkan bersama.

**Comment by herpiko** [comment]
Kamis, 26 November 2020, 19.00 - 20.30 WIB, di Google Meet (dengan recording, URL disediakan tim BlankOn)

Kuota maks 10 orang.

Skup materi (masih bisa diobok2 oleh pemateri):
  - Jurnalistik (influencing/menarik)
  - Konten sosmed
  - Kaidah

Tim yang (saya rasa) wajib ikut:
  - Humas
  - Dokumentasi
  - Kesenian

Bertentangan dengan usulan kemarin soal lokakarya dipublikasikan secara live, yang ini internal dulu.

Timbal balik dari kita: publikasi/iklan untuk narasumber/perusahaan narasumber
  - FB, Twitter, IG
  - Blog

Mohon nama anggota timnya yang akan diikutkan didaftarkan kemari (tulis di komentar) cc pak @slamets75 @raniaamina @FaiqAminuddin

**Comment by raniaamina** [comment]
Kesenian:
- Bayu Aji
-

**Comment by slamets75** [comment]
Humas
- Slamet Santoso `slamets75@gmail.com`
- 
-

**Comment by herpiko** [comment]
Tim Dokumentasi:
- @FaiqAminuddin

**Comment by herpiko** [comment]
Setiap peserta diminta untuk menyiapkan alat tulis fisik (kertas dan ballpoint).

**Comment by FaiqAminuddin** [comment]
Tim Dokumentasi:
@trisfaizal

**Comment by levay08** [comment]
> Humas:
> 
> * Slamet Santoso `slamets75@gmail.com`

* Levay

**Comment by LevryKurniawan** [comment]
Humas:
 
* Slamet Santoso `slamets75@gmail.com`
* Levay
* Levry `levry.k@gmail.com`

**Comment by umulsidikoh** [comment]
> Tim Dokumentasi:

- @FaiqAminuddin 
- @trisfaizal 
- @umulsidikoh

**Comment by samsulmaarif** [comment]
Pak @FaiqAminuddin @trisfaizal @levay08 dan bu @umulsidikoh boleh disertakan alamat surel masing-masing? 

Jika tidak berkenan untuk ditampilkan di publik boleh japri saya untuk saya undang di acara di kalender gmeet. 

Terima kasih.

**Comment by umulsidikoh** [comment]
> Pak @FaiqAminuddin @trisfaizal @levay08 dan bu @umulsidikoh boleh disertakan alamat surel masing-masing?
> 
> Jika tidak berkenan untuk ditampilkan di publik boleh japri saya untuk saya undang di acara di kalender gmeet.
> 
> Terima kasih.

Baik. Saya japri ya, Pak.

**Comment by FaiqAminuddin** [comment]
@samsulmaarif dampuawang@gmail.com

**Comment by levay08** [comment]
> Pak @FaiqAminuddin @trisfaizal @levay08 dan bu @umulsidikoh boleh disertakan alamat surel masing-masing?
> 
> Jika tidak berkenan untuk ditampilkan di publik boleh japri saya untuk saya undang di acara di kalender gmeet.
> 
> Terima kasih.

@samsulmaarif dorayakicool@gmail.com

**Comment by trisfaizal** [comment]
> Pak @FaiqAminuddin @trisfaizal @levay08 dan bu @umulsidikoh boleh disertakan alamat surel masing-masing?
> 
> Jika tidak berkenan untuk ditampilkan di publik boleh japri saya untuk saya undang di acara di kalender gmeet.
> 
> Terima kasih.

trisfaizal@gmail.com

**Comment by samsulmaarif** [comment]
Halo Bapak/Ibu peserta Lokakarya, bagi yang sudah setor surel silakan periksa surel atau _google calendar_ masing-masing, lalu konfirmasi kehadiran dengan menekan tombol Ya/Yes pada acara `Lokakarya BlankOn-dev: Copywriting`.

Terima Kasih.

**Comment by herpiko** [comment]
# Pekerjaan Rumah

Bikin berita tentang rilis jahitan pertama blankon yang sukses, kirim ke andro.medh4@gmail.com dengan subjek: Tugas Menulis, tenggat 10 hari dari sekarang (6 Desember 2020)

**Comment by herpiko** [comment]
Foto tangkapan layar, siapa tau mau diangkut ke blog nanti.

![Screenshot from 2020-11-26 20-20-47](https://user-images.githubusercontent.com/2534060/100367483-ded70c00-3034-11eb-88a0-dbbfb7fad39a.png)
![Screenshot from 2020-11-26 19-12-35](https://user-images.githubusercontent.com/2534060/100367505-e4cced00-3034-11eb-9bf5-9dfb5903715f.png)
![Screenshot from 2020-11-26 19-39-03](https://user-images.githubusercontent.com/2534060/100367514-ea2a3780-3034-11eb-956b-b89b270f7ad1.png)

**Comment by herpiko** [comment]
cc Pak @slamets75 dkk, sudah bisa disodok ke publik, https://www.youtube.com/watch?v=CcYWuSQ7PBI&feature=youtu.be

**Comment by tuanpembual** [comment]
hanya 2 orang yang mengirimkan umpan balik. belum dapat dibuat sesi selanjutnya.
Tiket saya tutup. Berita kegiatan sudah ada di beranda.
