### ISSUE TITLE
Perbaikan pada laman Memulai.md

### ISSUE THREAD

**Issue by ricocwp** [BlankOn/Verbeek#123]
Pada bagian Tim Pengembang BlankOn:

- [x] https://github.com/BlankOn/wiki/blob/master/TimPengembang/Infrastruktur/Infrastruktur.md
- [x] https://github.com/BlankOn/wiki/blob/master/TimPengembang/Riset/Riset.md
- [x] https://github.com/BlankOn/wiki/blob/master/TimPengembang/Pemaket/Pemaket.md
- [x] https://github.com/BlankOn/wiki/blob/master/TimPengembang/Kesenian/Kesenian.md
- [x] https://github.com/BlankOn/wiki/blob/master/TimPengembang/JaminanKualitas/JaminanKualitas.md
- [x] https://github.com/blankon-packages/https://github.com/blankon/
- [x] https://github.com/BlankOn/wiki/blob/master/TimBlankOn.md

Masih belum tersinkronisasi dengan tautan https://github.com/BlankOn/wiki/blob/master/Memulai.md

**Comment by samsulmaarif** [comment]
@ricocwp silakan dicek kembali, jika sudah ok silakan tutup tiket ini.

**Comment by ricocwp** [comment]
Baik pak, terima kasih..
