### ISSUE TITLE
Survey Target Pengguna

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#125]
Bisa pakai gform atau semacamnya. Kisi-kisi:

- Mereka pengen ada apa aja di distribusi linuxnya
- Sehari-hari pake apa aja
- Pekerjaannya apa
- Silakan ditambahkan lagi.

@Cengkaruk Mohon tentukan tenggatnya juga.

**Comment by Cengkaruk** [comment]
Pertanyaan saya bagi jadi 3 bagian.
- Identitas
- Penggunaan sistem operasi dan perangkat lunak secara umum
- Penggunaan perangkat lunak bebas dan terbuka

Minta masukan apa yang kurang atau yang perlu diperbaiki. Minta alamat surel untuk bisa saya invitasi ke formulir.

https://forms.gle/bkkW33VqTxGMy4eD7

Usul saya pak @herpiko ini perlu di ujicoba ke teman-teman pengembang.

**Comment by herpiko** [comment]
@Cengkaruk akur dengan garis besar dan ujicoba.

Alamat surel saya di herpiko@gmail.com

**Comment by herpiko** [comment]
Tiket ini saya buka kembali dan letakkan di in-progress supaya tidak tenggelem/terlupakan.

Tim Humas cc pak @slamets75 apakah bisa dibikinkan ceklis di sini tentang kanal mana aja yang sudah disodok untuk menyebarkan survey ini?

**Comment by herpiko** [comment]
Survey sudah dijelaskan dan hasilnya sudah dibeberkan oleh mas @Cengkaruk. Kesimpulannya:
- Target pengguna rilis: pekerja IT
- https://github.com/BlankOn/Verbeek/issues/126
