### ISSUE TITLE
Catatan Rapat Pengembang 20201120

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#127]
Mohon dirapikan dan dibawa ke wiki. https://gist.github.com/herpiko/153f4d524f3fe88f69826187ad0b78bc

Beranak:
- https://github.com/BlankOn/Verbeek/issues/126
- https://github.com/BlankOn/Verbeek/issues/125

**Comment by herpiko** [comment]
@FaiqAminuddin @umulsidikoh @trisfaizal ada yang bisa bawa ini ke wiki supaya bisa ditutup?

**Comment by FaiqAminuddin** [comment]
@herpiko Siap

**Comment by FaiqAminuddin** [comment]
Catatan BlankOngkow sudah saya taruh di sini https://github.com/BlankOn/wiki/blob/master/TimPengembang/Dokumentasi/Rapat/CatatanRapat20201120.md

**Comment by herpiko** [comment]
@FaiqAminuddin Terima kasih pak Faiq.
