### ISSUE TITLE
Pasang SSL *.boi donasi dari Radnet

### ISSUE THREAD

**Issue by samsulmaarif** [BlankOn/Verbeek#128]
Pasang ke:

- [x] Rani
- [x] Alynne

Berkas ada di saya.

Berkas yang perlu dipasang:
- berkas kunci
- berkas sertifikat
- berkas sertifikat intermediate

Mounting ke kontainer envoy di direktori `/etc/ssl/*.pem` (lihat di envoy.yaml dan docker-compose.yml)

**Comment by kudaliar032** [comment]
Sertifikat sudah saya pasang di server [Rani](https://rani.blankonlinux.or.id/) dan [Alynne](http://alynne.blankonlinux.or.id/) pak @samsulmaarif, monggo diperiksa

**Comment by samsulmaarif** [comment]
Sip
