### ISSUE TITLE
Undangan "podcast santai" Sinau dari komunitas pengguna Slims Jakarta

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#129]
Waktu sinaunya antara 2 sampai 3 jam di akhir pekan, pemaparan bisa 30-45 menit. selebihnya diskusi.

Topik ringan terkait pengenalan gnu/linux, cerita tentang proyek blankon, suka duka pengembangan. Kanal akan disiapkan oleh koordinator Slims Jakarta

Silakan dicomot bagi yang mau wakilin.

**Comment by slamets75** [comment]
untuk detail waktu kapan diadakan pak @herpiko ?

**Comment by slamets75** [comment]
**Kisi-kisi podcast santai bersama komunitas penggun slims jakarta**

1. pengenalan open source dan gnu/linux
2. BlankOn
 - awal berdiri
 - tujuan proyek
 - tentang tim pengembang
 - produk BlankOn 

3. Suka duka pengembangan
4. Closing (Ajakan kontribusi)

**Comment by herpiko** [comment]
Besok sabtu diajak ngobrol internal dulu sama slims pukul 16.00 WIB.

**Comment by herpiko** [comment]
- Hari sabtu tanggal 19 Desember 2020, pukul ?
- Demokan slims yang jalan di atas sistem operasi BlankOn

**Comment by herpiko** [comment]
Dari Slims butuh:
- Nama dan foto narasumber

**Comment by slamets75** [comment]
> - Hari sabtu tanggal 19 Desember 2020, pukul 09.00-12.00
> - Demokan slims yang jalan di atas sistem operasi BlankOn

Ok saya ambil ini pak, saya pasang di laptop buat demo, kebetulan pernah terkini slims 9 bulian.

**Comment by herpiko** [comment]
@slamets75 Secara keseluruhan perlu,

- Garap salindia
- Tentukan mau utus siapa, nama dan foto narasumber kirim ke pak Ibnu, ditunggu 1 desember.
- Virtualbox uluwatu dengan slims yang berjalan di atasnya

Ini dibagi-bagi aja pak atau garap barengan, jangan digarap sendirian.

**Comment by slamets75** [comment]
Nama Narasumber Sinau dari komunitas pengguna Slims Jakarta 
1. Herpiko Dwi Aguno
2. Estu Fardani
3. Slamet Santoso

**Comment by herpiko** [comment]
Salindia disikat pak @slamets75. Perlu tektokan tanggal Selasa 8 Desember 2020, 19.00 WIB.

**Comment by herpiko** [comment]
@FaiqAminuddin @umulsidikoh @trisfaizal tim dok ada yang mau nyoba garap laporan beritanya?

**Comment by FaiqAminuddin** [comment]
@herpiko Saya coba malam ini

**Comment by FaiqAminuddin** [comment]
**Rancangan Laporan Berita**

BlankOn dan Slims Perangkat Lunak Terbuka
===

Sabtu, 19 Desember 2020 tim pengembang BlankOn mendapat kesempatan untuk berbagi pengalaman pada acara Sinau Daring Slims Jakarta. Acara yang diselenggarakan secara daring di Zoom Meeting ini merupakan hasil kerjasama komunitas pengguna Slims Jakarta, Perpustakaan Kemendikbud dan BlankOn.

BlankOn dan Slims, keduanya merupakan perangkat lunak yang bersifat _open source_. Slims adalah aplikasi otomasi perpustakaan _open source_ yang dapat diterapkan pada berbagai sistem operasi termasuk pada sistem operasi BlankOn Linux.

Sebagai pengantar, Pahlevy Tawainella menyampaikan tentang pentingnya open source dan Linux kemudian disambung perkenalan tentang BlankOn oleh pak Estu Fardani. Sebagai pengembang yang sudah lama aktif di BlankOn bercerita tentang  BlankOn yang lahir pada tahun 2004. Sampai sekarang BlankOn sudah merilis 11 distribusi Linux dan beberapa produk lainnya seperti, Manokwari, Ridon, Tendang dan lain-lain.

Selanjutnya Pak Slamet Santoso dan Pak Herpiko memaparkan lebih rinci tentang pengembang dan kontributor yang ada di BlankOn beserta cakupan kerjanya. Untuk ikut berpartisipasi pada proyek dan rilis BlankOn, seseorang tidak harus ahli IT dan mempunyai waktu luang yang banyak. BlankOn selalu terbuka bila ada yang ingin bergabung ikut menjadi pengembang atau ikut berkontribusi atau hanya usul dan melaporkan kutu.

Selanjutnya, pak Herpiko memperagakan proses instalasi sistem operasi BlankOn dan pemasangan Slims pada Linux menggunakan Docker. Adapun sebagai tindak lanjutnya, tim pengembang BlakOn berencana mempaketkan Slims Burlian versi debian sehingga lebih mudah dipasang.

![image](https://user-images.githubusercontent.com/10925212/102694376-800e4800-4218-11eb-97bd-191790a63bfd.png)

**Comment by raniaamina** [comment]
@FaiqAminuddin BlankOn selalu terbuka bila ada yang ingin bergabung ikut menjadi pengembang atau ikut berkontribusi atau hanya usul dan melaporkan kutu. 


BlankOn selalu terbuka untuk siapa saja yang ingin berkontribusi dalam bentuk kode, kesenian, sponsor, berbagi id/usulan pengembangan, pelaporan kutu, dan lain sebagainya, atau bahkan menjadi pengembang tetap. 

----
Otomasi => otomatisasi

**Comment by herpiko** [comment]
@FaiqAminuddin minta tolong di-PR-kan ke beranda supaya tiket ini bisa kita tutup.

Terima kasih bapak-bapak semuanya.

Tiket turunan: https://github.com/BlankOn/Verbeek/issues/213

**Comment by FaiqAminuddin** [comment]
siap

**Comment by FaiqAminuddin** [comment]
@herpiko eh ini saya mau PR lagi lewat gitHub dari FaiqAminuddin/beranda, kok PR yang lalu (berita tentang gitg) ikut lagi. Apakah memang seperti itu?

**Comment by herpiko** [comment]
@FaiqAminuddin perlu lokakarya git dulu berti ya.

**Comment by samsulmaarif** [comment]
Sudah dilaksanakan.
