### ISSUE TITLE
Kabar berita: keputusan rapat

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#137]
Sumber: https://www.youtube.com/watch?v=iTEYTplXCBc

**Comment by herpiko** [comment]
Mohon tim Dokumentasi atau tim Humas tiket ini dicomot, bisa dicicil dulu tulisannya.

Tiket ini bergantung kepada tiket https://github.com/BlankOn/Verbeek/issues/108

**Comment by tuanpembual** [comment]
ini sepertinya belum layak ke bernada pak, skip dulu.
tiket saya tutup.
