### ISSUE TITLE
Catatan Instalasi Pertama Jahitan Harian 20201122-5

### ISSUE THREAD

**Issue by leonyonz** [BlankOn/Verbeek#140]
# Spesifikasi Mesin

- KVM
- 2vCPU
- 2GB RAM
- 15GB SSD

# Melalui Installer Boot Menu

1. Tampilan Boot Menu

![image](https://user-images.githubusercontent.com/42370275/99967792-e1cec400-2dca-11eb-9b2f-c4dbdb854afb.png)

2. Pilih Start Installer

![image](https://user-images.githubusercontent.com/42370275/99967915-07f46400-2dcb-11eb-87aa-35fe3f6cbeda.png)

3. Tampilan Pilih Bahasa

![image](https://user-images.githubusercontent.com/42370275/99967991-26f2f600-2dcb-11eb-8a6b-eee83bac5bef.png)

4. Tampilan Pilih Lokasi

![image](https://user-images.githubusercontent.com/42370275/99968048-383c0280-2dcb-11eb-8614-520e98a5d350.png)

5. Tampilah Pilih Pengaturan Keyboard

![image](https://user-images.githubusercontent.com/42370275/99968254-80f3bb80-2dcb-11eb-8020-35a63880d721.png)

6. Terdapat warning setelah menekan tombol next.

![image](https://user-images.githubusercontent.com/42370275/99968315-92d55e80-2dcb-11eb-9b39-ace93f324c10.png)

7. Tampilan Menu Instalasi

![image](https://user-images.githubusercontent.com/42370275/99968365-a1237a80-2dcb-11eb-8837-47c83038bf17.png)

8. Stop

# Melalui Live Mode

1. Tampilan Booting Up

![image](https://user-images.githubusercontent.com/42370275/99968901-53f3d880-2dcc-11eb-99a0-2c5acffd0bd3.png)

2. Tampilan Desktop Live Mode

![image](https://user-images.githubusercontent.com/42370275/99968992-74bc2e00-2dcc-11eb-8fe7-9b1546450829.png)

3. Tampil Interface Installer Live Mode

![image](https://user-images.githubusercontent.com/42370275/99969201-b9e06000-2dcc-11eb-9410-96dec472ee3d.png)

4. Tampilan Pilih Bahasa

![image](https://user-images.githubusercontent.com/42370275/99969305-d7adc500-2dcc-11eb-8cb2-6a10b0bea9a7.png)

- **Catatan**: Terdapat karakter/symbol font yang tidak terbaca

5. Tampilan Pilih Lokasi

![image](https://user-images.githubusercontent.com/42370275/99969382-f0b67600-2dcc-11eb-8a44-fd31023709a0.png)

6. Tampilan Pengaturan Keyboard Indonesia

![image](https://user-images.githubusercontent.com/42370275/99969481-18a5d980-2dcd-11eb-8e9e-ff7e6364754b.png)

- **Catatan:** Pengaturan keyboard default untuk bahasa indonesia memiliki layout arabic

7. Tampilan Pengaturan Keyboard Inggris

![image](https://user-images.githubusercontent.com/42370275/99969630-586cc100-2dcd-11eb-80eb-f13ca61b9258.png)

8. Tampilan Pilih Perangkat Instalasi

![image](https://user-images.githubusercontent.com/42370275/99969684-67ec0a00-2dcd-11eb-8838-d617ac3d9a36.png)

9. Tampilan Pilih Tipe Disk

![image](https://user-images.githubusercontent.com/42370275/99969826-94078b00-2dcd-11eb-98de-2ef98921c0a4.png)

10. Tampilan Buat Paritisi

![image](https://user-images.githubusercontent.com/42370275/99969949-bdc0b200-2dcd-11eb-9570-d8183d4cd17c.png)

11. Tampilan Partisi

![image](https://user-images.githubusercontent.com/42370275/99970188-15f7b400-2dce-11eb-837b-df0c7702723a.png)

![image](https://user-images.githubusercontent.com/42370275/99970322-3a539080-2dce-11eb-87c0-ae41faf32f95.png)

12. Tampilan Pengaturan User

![image](https://user-images.githubusercontent.com/42370275/99970394-55260500-2dce-11eb-998e-ba0ef137fec7.png)

13. Tampilan Rangkuman Instalasi

![image](https://user-images.githubusercontent.com/42370275/99970438-68d16b80-2dce-11eb-9e13-20d17f8afa5c.png)

14. Tampilan Proses Instalasi

![image](https://user-images.githubusercontent.com/42370275/99970487-7c7cd200-2dce-11eb-96ce-3bc12ce34168.png)

15. Tampilan Installer Selesai

![image](https://user-images.githubusercontent.com/42370275/99971110-57d52a00-2dcf-11eb-8a00-4bada941ae2c.png)

- **Catatan**: Pada tombol Selesai bertuliskan "Kelar" (apakah typo)

16. Tampilan Grub

![image](https://user-images.githubusercontent.com/42370275/99971461-c31efc00-2dcf-11eb-8788-e82e2f67db42.png)

17. Tampilan layar login

![image](https://user-images.githubusercontent.com/42370275/99971535-da5de980-2dcf-11eb-9758-3974e62c5308.png)

18. Tampilan Desktop

![image](https://user-images.githubusercontent.com/42370275/99971621-06796a80-2dd0-11eb-82bd-7f5f05e8a08a.png)

19. Update Repo

![image](https://user-images.githubusercontent.com/42370275/99973199-15f9b300-2dd2-11eb-9c25-05351ef241ac.png)

- **Catatan:** Tidak mengarah ke repo BlankOn

20. Selesai.

**Comment by herpiko** [comment]
@leonyonz @mdzulkifli Kira-kira bagaimana mekanisme laporan uji yang enak supaya hal-hal yang mengganggu/tidak sesuai ekspektasi dapat ditindaklanjuti oleh tim pemaket dan riset?

Apakah (pilih salah satu):
- Begitu ada temuan langsung bikin tiket terpisah untuk setiap item, misal berdasar pengujian di atas ditemukan:
  - Lumbung tidak mengarap ke arsip-dev
  - Ada karakter yang tidak dikenali di antar muka pemasang sistem operasi
  - Pilihan model papan bikin rancu, saat diklik Indonesia, papan diganti ke tulisan arab dan kawi
- Laporan lengkap semacam ini (ini contoh yang bagus!) dikumpulkan di MR terkait (misal pada jahitan di atas, MR-nya ada di https://github.com/BlankOn/blankon-live-build/pull/11), lalu bikinkan setiap tiket turunan seperti halnya di atas di repo verbeek/issues.

**Comment by leonyonz** [comment]
Tim JK ada rencana rapat hari jumat, mungkin bisa sekalian dibicarakan Pak @mdzulkifli

**Comment by herpiko** [comment]
@leonyonz @mdzulkifli Mantul jabrik.

Karena kita sedang menuju open governance, sebisa mungkin rapatnya menggunakan fasilitas gmeet dari pak @samsulmaarif atau pak @slamets75 supaya dapat menggunakan fitur rekaman. Setiap rapat perlu ada tiket supaya catatan rapat bisa dirangkum di tiket dahulu sebelum dibawa ke wiki.

**Comment by leonyonz** [comment]
Noted Pak, kebetulan saya juga ada akun gsuite yang bisa dibuat rekam namun kawatirnya device saya yang gak mampu hehehe, paralel nanti minta bantuannya Pak @samsulmaarif

**Comment by herpiko** [comment]
Saya menemukan ini di milis, pesan-pesan surel dari tahun 2013, https://groups.google.com/g/blankon-tiket/c/FwMfscGOXv0.

Saya coba rangkum polanya begini (secara berurutan):
- JK menemukan kutu abc di jahitan 001.
- JK bikin tiket X: Kutu abc terjadi di jahitan 001
- Jahitan 002 dirilis
- JK menguji dan kutu masih terjadi, JK mengomentari tiket X, "Masih terjadi di jahitan 002"
- Jahitan 003 dirilis
- JK menguji dan kutu masih terjadi, JK mengomentari tiket X, "Masih terjadi di jahitan 003, namun ada kemajuan p, q dan r, dst"
- Jahitan 004 dirilis
- JK menguji dan kutu sudah tidak terjadi lagi, JK mengomentari tiket X, "Sudah tidak terjadi lagi di jahitan 004"
- JK menutup tiket X.


Barangkali dapat dipertimbangkan dalam bahasan rapat.

**Comment by leonyonz** [comment]
Hi Pak @herpiko untuk review jahitan 20201123-1 apakah dilanjut aja pada tiket ini atau buat tiket baru.

**Comment by herpiko** [comment]
> Hi Pak @herpiko untuk review jahitan 20201123-1 apakah dilanjut aja pada tiket ini atau buat tiket baru.

Usulan saya dibikinkan tiket terpisah, yang ini bisa ditutup. Untuk jahitan baru ke depannya bisa langsung bikin tiket spesifik ke masalah/kutu dengan menyertakan identitas jahitan, deskrpisi masalah dan tangkapan layar yang relevan.

**Comment by leonyonz** [comment]
Oke Siap, di ulik dulu jahitannya.
