### ISSUE TITLE
Aktifkan GitHub Action untuk Repo Wiki

### ISSUE THREAD

**Issue by samsulmaarif** [BlankOn/Verbeek#146]
Karena sepertinya berkas `.travis.yml` di repo Wiki [dihapus](https://github.com/BlankOn/wiki/commit/9196d131229fae2b99d2ab6f3796be30ae1dff48) dan _deployment_ ke dev.blankonlinux.or.id pun terhenti, ini saatnya untuk menggunakan _GitHub Action_ dengan ketentuan sebagai berikut:

- [x] repo Wiki yang dimaksud adalah https://github.com/BlankOn/wiki
- [x] jalankan hanya di cabang master
- [x] buat _pipeline_ agar dijalankan secara manual, tidak ada pembangunan otomatis (automatic build) alasannya karena kadang pengembang menyunting langsung melalui GitHub, dan kadang menyunting beberapa berkas secara hampir bersamaan, 1 berkas akan ada 1 commit, jadi baiknya untuk proses deploy dibuat secara manual saja. 
- [x] usul saya, nanti yang melakukan deploy adalah tim Dokumentasi cc pak @FaiqAminuddin dengan pertama kali akan dipandu oleh tim infra cc @kudaliar032

**Comment by kudaliar032** [comment]
Pak @FaiqAminuddin, untuk deployment wiki menggunakan GitHub Actions telah saya aktifkan. Nantinya tim dokumentasi bisa mengikuti panduan berikut [manual deployment blankon wiki](https://gist.github.com/kudaliar032/9efbe0c3627602fc66797ca9981bc64e) untuk melakukan deployment wiki terbaru. Terima kasih

**Comment by FaiqAminuddin** [comment]
terima kasih pak @kudaliar032
