### ISSUE TITLE
Uji Lumbung Uluwatu arsip.boi

### ISSUE THREAD

**Issue by samsulmaarif** [BlankOn/Verbeek#147]
Mohon bantuan tim JK untuk menguji repo Uluwatu, kira-kira langkahnya adalah sebagai berikut:

- [x] Unduh iso [Uluwatu](https://cdimage.blankonlinux.or.id/blankon/rilis/11.0.1/BlankOn-11.0.1-desktop-amd64.iso) 
- [x] Jalankan di VM atau live USB
- [x] Lakukan `sudo apt-get update` | pastikan repo mengarah ke arsip.boi
- [x] pasang paket sembarang, misal `sudo apt install vlc` dan paket-paket acak lainnya
- [x] Hasilnya diketikkan di komentar tiket ini

Terima kasih. 

Tiket terkait :
- #142

**Comment by samsulmaarif** [comment]
@samsulmaarif pak @wd549 dan tim mohon bantuan ya... Terima kasih

**Comment by leonyonz** [comment]
Pak @samsulmaarif perlu diinstall terlebih dahulu atau dari live mode saja ?

**Comment by samsulmaarif** [comment]
@leonyonz bisa dicoba live dulu, catat hasilnya, setelah sukses coba lagi setelah instalasi catat juga hasilnya

**Comment by leonyonz** [comment]
Ok dicoba

**Comment by leonyonz** [comment]
### Spesifikasi Mesin
- 2 vCPU
- 2GB RAM
- 20GB Disk
- KVM

### Uji Live

- Arahkan repo ke http://arsip.blankonlinux.or.id/blankon/

![image](https://user-images.githubusercontent.com/42370275/100250542-5abb5080-2f70-11eb-8efa-07da5d53716e.png)

- Menjalankan update paket : `apt update`

![image](https://user-images.githubusercontent.com/42370275/100250662-7de60000-2f70-11eb-9364-0bbf2e5adc1a.png)
Output:
```
Get:1 file://lib/live/mount/medium/repo uluwatu InRelease
Ign:1 file://lib/live/mount/medium/repo uluwatu InRelease
Get:2 file://lib/live/mount/medium/repo uluwatu Release [1,314 B]
Get:2 file://lib/live/mount/medium/repo uluwatu Release [1,314 B]
Get:3 file://lib/live/mount/medium/repo uluwatu Release.gpg
Ign:3 file://lib/live/mount/medium/repo uluwatu Release.gpg
Ign:4 http://arsip.blankonlinux.or.id/blankon uluwatu InRelease
Get:5 http://arsip.blankonlinux.or.id/blankon uluwatu Release [18.3 kB]
Get:6 http://arsip.blankonlinux.or.id/blankon uluwatu Release.gpg [836 B]
Get:7 http://arsip.blankonlinux.or.id/blankon uluwatu/main amd64 Packages [7,907 kB]
Get:8 http://arsip.blankonlinux.or.id/blankon uluwatu/restricted amd64 Packages [79.9 kB]
Get:9 http://arsip.blankonlinux.or.id/blankon uluwatu/extras amd64 Packages [57.8 kB]
Fetched 8,064 kB in 4s (2,111 kB/s)                       
Reading package lists... Done
Building dependency tree       
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
```

- Melakukan instalasi paket htop :

![image](https://user-images.githubusercontent.com/42370275/100251043-e634e180-2f70-11eb-99a7-02695e265124.png)

- Melakukan instalasi paket Neofetch

![image](https://user-images.githubusercontent.com/42370275/100251116-fa78de80-2f70-11eb-90cf-2f32ff8a3587.png)

- Melakukan instalasi paket Tmux : 

![image](https://user-images.githubusercontent.com/42370275/100252375-60199a80-2f72-11eb-82ff-2ae0542ae2ca.png)

**Comment by herpiko** [comment]
@slamets75 Perlu:

- Siapkan konten pengumuman.
- Siapkan daftar kanal yang akan dilemparkan konten dalam bentuk checklist (lihat contoh di deskripsi tiket)
- Sodok satu-satu.

**Comment by herpiko** [comment]
@leonyonz Kesimpulannya bagaimana berti pak? Sudah aman untuk dibawa ke pengguna?

**Comment by herpiko** [comment]
@slamets75 Persiapan woro-woronya bagaimana pak?

**Comment by leonyonz** [comment]
Hi Pak @herpiko @samsulmaarif  mohon maaf terlewat.

Udah dicoba mode live dan instalasi pada mesin langsung, untuk lumbung http://arsip.blankonlinux.or.id/blankon/ tidak ada kendala saat instalasi beberapa paket seperti report saya sebelumnya.

Apabila dari sisi mesin lumbung sudah siap untuk menangani permintaan maka seharusnya sudah aman Pak.

**Comment by herpiko** [comment]
cc @slamets75 dan tim.

**Comment by herpiko** [comment]
Ini saya tutup ya, tiket susulan ada di https://github.com/BlankOn/Verbeek/issues/162

Terima kasih pak @leonyonz @samsulmaarif @slamets75

**Comment by ainulhakim** [comment]
boleh buka lagi ya

Err:1 http://arsip.blankonlinux.or.id/blankon uluwatu/main amd64 libavdevice57 amd64 7:3.4.2-1
  404  Not Found [IP: 202.154.57.165 80]
Err:2 http://arsip.blankonlinux.or.id/blankon uluwatu/main amd64 libobs0 amd64 19.0.3+dfsg1-1+b1
  404  Not Found [IP: 202.154.57.165 80]
Err:3 http://arsip.blankonlinux.or.id/blankon uluwatu/main amd64 obs-plugins amd64 19.0.3+dfsg1-1+b1
  404  Not Found [IP: 202.154.57.165 80]
Err:4 http://arsip.blankonlinux.or.id/blankon uluwatu/main amd64 obs-studio amd64 19.0.3+dfsg1-1+b1
  404  Not Found [IP: 202.154.57.165 80]
Unable to correct missing packages.
E: Failed to fetch http://arsip.blankonlinux.or.id/blankon/pool/main/f/ffmpeg/libavdevice57_3.4.2-1_amd64.deb  404  Not Found [IP: 202.154.57.165 80]
E: Failed to fetch http://arsip.blankonlinux.or.id/blankon/pool/main/o/obs-studio/libobs0_19.0.3+dfsg1-1+b1_amd64.deb  404  Not Found [IP: 202.154.57.165 80]
E: Failed to fetch http://arsip.blankonlinux.or.id/blankon/pool/main/o/obs-studio/obs-plugins_19.0.3+dfsg1-1+b1_amd64.deb  404  Not Found [IP: 202.154.57.165 80]
E: Failed to fetch http://arsip.blankonlinux.or.id/blankon/pool/main/o/obs-studio/obs-studio_19.0.3+dfsg1-1+b1_amd64.deb  404  Not Found [IP: 202.154.57.165 80]
E: Aborting install.

**Comment by samsulmaarif** [comment]
pak @ainulhakim apakah bisa dinformasikan langkah untuk mereproduksi isu ini? Apakah bapak menggunakan uluwatu yang _fresh install_ atau pemasangan lama? 

cc tim JK @mdzulkifli dkk

**Comment by herpiko** [comment]
Belum ada laporan lagi.
