### ISSUE TITLE
Jahitan: lumbung terkonfigurasi ganda

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#148]
### Langkah reproduksi

Terjadi di jahitan 20201125-14. Jalankan `sudo apt update`

### Masalah

Selain /etc/apt/source.list, ada lagi di dalam /etc/apt/source.list.d/

Dapat pesan warning berikut,
![Screenshot from 2020-11-26 00-18-11](https://user-images.githubusercontent.com/2534060/100261193-f9e64500-2f7c-11eb-895b-5f90f8d27d08.png)

### Ekspektasi
Mestinya lancar apt update tanpa warning/galat dan berkast *.list yang terdaftar di bawah /etc/apt hanya satu, yaitu /etc/apt/source.list.

**Comment by leonyonz** [comment]
On check Pak

**Comment by leonyonz** [comment]
Hi Pak @herpiko untuk jahitan 20201125-14 sepertinya di mesin saya normal Pak untuk `sudo apt update` :

![image](https://user-images.githubusercontent.com/42370275/100269474-2bfda400-2f89-11eb-93ab-0fe79a310f1b.png)

Jika dicek di cek untuk list reponya ada 2 di `/etc/apt/source.list` dan `/etc/apt/source.list.d/default_repository.list`

- `/etc/apt/source.list`

![image](https://user-images.githubusercontent.com/42370275/100269595-6109f680-2f89-11eb-90e1-3e21b8419327.png)

- `/etc/apt/source.list.d/default_repository.list`

![image](https://user-images.githubusercontent.com/42370275/100269638-70893f80-2f89-11eb-9fff-ae8a34962a0c.png)

Terlampir hasil uji install paket acak : 

![image](https://user-images.githubusercontent.com/42370275/100269759-9dd5ed80-2f89-11eb-9abd-0263b38f27ea.png)

**Comment by herpiko** [comment]
Sudah aman per https://cdimage.blankonlinux.or.id/blankon/jahitan-harian/20201129-14/

![Screenshot from 2020-11-29 13-52-57](https://user-images.githubusercontent.com/2534060/100535301-90ca3000-320f-11eb-868d-8a3a005c1453.png)
