### ISSUE TITLE
Jahitan: nama OS di GNOME/Settings/About masih bawa string Debian bullseye/sid. Paketkan base-files

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#150]
### Langkah reproduksi

Terjadi di jahitan 20201125-14. Buka Settings lalu klik menu About.

### Masalah

Pada bagian OS Name, masih mengandung string `Debian GNU/Linux bullseye/sid`. 

![Screenshot from 2020-11-26 00-35-06](https://user-images.githubusercontent.com/2534060/100263006-872a9900-2f7f-11eb-8732-49bbfd591b46.png)

### Ekspektasi

Sesuai pedoman alih merek Debian, ini perlu diganti jadi `BlankOn Linux 12.0 Verbeek`

**Comment by leonyonz** [comment]
Hi Pak @herpiko valid ya Pak, 

![image](https://user-images.githubusercontent.com/42370275/100270360-88ad8e80-2f8a-11eb-802b-c1804155fc96.png)

**Comment by artemtech** [comment]
String Debian bullseye/sid ini ada di /etc/os-release, yang merupakan
symlink dari /usr/lib/os-release

ada paket yang mengatur ini, yaitu `base-files`.
bisa nanti untuk tim pemaket melakukan perubahan atas itu, daripada nanti
melakukan inject paket ke dalam chroot

https://github.com/blankon-packages/base-files

**Comment by herpiko** [comment]
@artemtech Siap, nanti saya revert.

**Comment by antosamalona** [comment]
Saya coba paketkan dulu, pak.

**Comment by herpiko** [comment]
@artemtech https://pastebin.com/mQsaPj3E

**Comment by leonyonz** [comment]
Hi Pak @herpiko Update per-jahitan 20201205-1 untuk nama OS sudah menggunakan BlankOn/Verbeek 

![image](https://user-images.githubusercontent.com/42370275/101279305-fb710200-37f3-11eb-9b85-7f353651bb57.png)

![image](https://user-images.githubusercontent.com/42370275/101279312-0a57b480-37f4-11eb-9d18-a69f9d30b2f7.png)
