### ISSUE TITLE
[Request] Penamaan ISO Jahitan Harian

### ISSUE THREAD

**Issue by leonyonz** [BlankOn/Verbeek#151]
Hi Pak @samsulmaarif @herpiko 

Mau request untuk penamaan berkas ISO jahitan harian apakah bisa disesuaikan agar tidak menggunakan prefix tanggal seperti sekarang ?

Mengacu ke tiket #93 sepertinya untuk `zsync` ini perlu keseragaman atas nama berkas ISO supaya bisa berjalan.

Jadi nantinya yang membedakan adalah direktori induknya saja.

Terima kasih.

### Referensi 

http://cdimage.ubuntu.com/daily-live/

**Comment by herpiko** [comment]
@leonyonz Konteksnya duplikat dengan tiket lain https://github.com/BlankOn/Verbeek/issues/93

**Comment by leonyonz** [comment]
Woke, Pak @herpiko dilanjut di tiket #93 saja jika demikian,
