### ISSUE TITLE
noVNC milik jk.boi Tidak Berfungsi di Belakang Envoy Proxy

### ISSUE THREAD

**Issue by samsulmaarif** [BlankOn/Verbeek#152]
Laman jk.boi sedianya digunakan oleh tim JK untuk menguji iso jahitan harian. Namun setelah implementasi envoy proxy di alynne, ada satu fitur penting yang menjadi tidak berfungsi, yaitu noVNC. Halaman jk.boi secara keseluruhan dapat diakses, fitur-fitur untuk mengelola (termasuk membuat, menghapus, memodifikasi) VM berfungsi dengan baik, kecuali fitur noVNC tadi. 

Pesan galat yang muncul adalah `Something went wrong, connection is closed`

![](https://i.imgur.com/bilnPyQ.png)

**Comment by herpiko** [comment]
@samsulmaarif Layanan ini perlu port berapa saja pak?

**Comment by leonyonz** [comment]
Portnya apakah sudah open Pak, kemaren pas deploy sempat dapat galat itu juga si
setelah open port 9500 - 95100 aman

**Comment by samsulmaarif** [comment]
Saat ini sudah bisa digunakan dengan tanpa protokol http (bukan https).

Topologi (dari belakang)

webvirtcloud (& novncd) <--- nginx (reverse proxy, 8001) <-- envoyproxy (http & https) <-- user


Sidik gangguan:

```
## tambahkan port nginx ke dalam konfigurasi webvirtcloud
vim /srv/webvirtcloud/webvirtcloud/settings.py

....
WS_PUBLIC_PORT = 8001
....

## buka port 8001 di dingap
vim /etc/csf/csf.conf

....
TCP_IN="port-lain-di-sini,8001"
TCP_OUT="port-lain-di-sini,8001"
....

## Restart csf & supervisor
systemctl restart supervisor
systemctl restart csf

## nonaktifkan redirect https di envoy
```

Coba akses dengan http://jk.boi

**Comment by samsulmaarif** [comment]
Mohon bantu tim JK untuk menguji fungsionalitas jk.boi

Skup uji:
- buka jk.boi (tanpa https)
- login dengan akun masing-masing (anggota tim JK)
- buat VM (atau gunakan VM yang ada)
- mount iso jahitan BlankOn yang terbaru
- nyalakan VM, lalu buka console (klik pada menu Access -> Console -> console)
- Silakan tutup tiket ini jika sudah muncul tampilan OS pada jendela console. 

Catatan tambahan untuk semua tim JK yang menggunakan jk.boi: 
- sebagai penanda kepemilikan instance, gunakan menu Settings -> Users -> Instance owners -> [+] -> pilih nama sendiri

/cc @mdzulkifli @ricocwp

**Comment by leonyonz** [comment]
On check Pak @samsulmaarif

**Comment by leonyonz** [comment]
Capture VM:

![image](https://user-images.githubusercontent.com/42370275/101269683-f71cf880-37a3-11eb-98bd-f11d0b9b454c.png)

Capture noVNC:

![image](https://user-images.githubusercontent.com/42370275/101269701-2c294b00-37a4-11eb-98b0-3118dd8b5b28.png)

![image](https://user-images.githubusercontent.com/42370275/101269711-43683880-37a4-11eb-85a7-c762d6f135c6.png)

Ijin tutup ya Pak @samsulmaarif
