### ISSUE TITLE
Sync lumbung arsip-dev ke sid setiap pukul 02.00 pagi setiap hari

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#155]
Asumsinya pukul 2 pagi itu pendekar udah capek ngoprek dan bobo. Kalau dilakukan setiap hari harusnya incrementalnya kecil dan tidak membebani bandwith.

Referensi: https://github.com/BlankOn/wiki/blob/master/TimPengembang/Infrastruktur/IrgshGo.md#sinkronisasi-dengan-hulu

**Comment by herpiko** [comment]
Isi cron palingan:
- Matikan layanan irgsh-chief untuk mencegah submit paket saat sinkronisasi berlangsung
- Sinkronisasi dengan hulu
- Nyalakan kembali irgsh-chief setelah sinkronisasi selesai

**Comment by samsulmaarif** [comment]
Ini sepertinya sudah dieksekusi oleh pak @herpiko sendiri ya? dan sepertinya juga sudah jalan.
