### ISSUE TITLE
Lokakarya Quality Assurance Engineer

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#156]
Perlu cari narasumber yang mau berbagi ke tim JK BlankOn.

**Comment by herpiko** [comment]
Pak @cho2 bersedia mengisi. Pak @mdzulkifli silakan diusulkan waktunya selain tanggal 19 Desember 2020 (ada Sinau dengan Slims). Dari pak Kukuh kisi-kisinya akhir pekan dan pagi (mungkin mulai jam 9).

**Comment by cho2** [comment]
Yuk mari

**Comment by mdzulkifli** [comment]
Pak @cho2, kami mengusulkan Lokakarya Jaminan Kualitas dilaksanakan pada
Hari, tanggal: Minggu, 12 Desember 2020
Pukul: 09.00 WIB s.d. selesai

Mohon kesediaan waktu Bapak.
Terima kasih.

**Comment by cho2** [comment]
Siap pak @mdzulkifli, saya bikin pengingat dulu biar tidak lupa.

**Comment by cho2** [comment]
> Hari, tanggal: Minggu, 12 Desember 2020

Ini 12 Desember ternyata Sabtu. Mau Sabtu atau Minggu?

**Comment by mdzulkifli** [comment]
Oh, iya, Pak, salah ketik, maksudnya itu hari Sabtu, 12 Desember 2020. Hari Sabtu semua anggota Tim JK aman.
Makasih Pak @cho2.

**Comment by herpiko** [comment]
Sudah terlaksana dengan baik. Terima kasih banyak pak @cho2 sudah meluangkan waktu dan tenaga.

Salindia (cerminan dari [sini](https://blog.kukuh.syafaat.id/slides/jaminan-kualitas-blankon/jaminan-kualitas-blankon.pdf)) : [jaminan-kualitas-blankon.pdf](https://github.com/BlankOn/Verbeek/files/5682908/jaminan-kualitas-blankon.pdf).

**Comment by cho2** [comment]
Terima kasih kembali :+1:
