### ISSUE TITLE
CD/CD irgsh: release-cli.tar.gz khusus untuk binary cli

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#160]
Saat ini release.tar.gz berukuran sekitar 50MB dan mengandung semua perkakas irgsh. Saat pemaket memperbarui perkakasnya, harusnya cukup mencomot tarball yang hanya mengandung binary irgsh-cli (saat ini ukurannya hanya 16MB).

Sesuaikan juga di installer-nya.

**Comment by kudaliar032** [comment]
pak @herpiko, kalau ini saya arahkan langsung upload binary filenya saja bagaimana? Jadi nanti installer juga langsung download binary file tidak perlu download dan extract file tarball.

**Comment by herpiko** [comment]
@kudaliar032 Boleh pak.

**Comment by kudaliar032** [comment]
Mohon untuk ditinjau PR berikut https://github.com/BlankOn/irgsh-go/pull/106 terkait tiket ini pak @herpiko. Terima kasih

**Comment by herpiko** [comment]
![Screenshot from 2020-11-28 23-03-11](https://user-images.githubusercontent.com/2534060/100519989-f39ad780-31cd-11eb-8f02-3e72cd416daf.png)

Sudah 15MB dan jauh lebih cepat pemasangannya. Trims banyak pak @kudaliar032 .
