### ISSUE TITLE
Buat berita (woro-woro) lumbung Uluwatu sudah bisa digunakan

### ISSUE THREAD

**Issue by slamets75** [BlankOn/Verbeek#162]
Mulai rangkai dengan ilmu copywriter kemarin ya tim Humas dengan kaidah 5W + 1H

**Comment by slamets75** [comment]
1. What - Apa yang di beritakan ?
2. Where - Dimana permasalahan lumbung Uluwatu terjadi ?
3. When - Kapan permasalahan lumbung Uluwatu terjadi ?
4. Why - Mengapa permasalahan lumbung Uluwatu terjadi ?
5. Who - Siapa yang terlibat dalam permasalahan lumbung Uluwatu tersebut ?

1. How - Bagaimana permasalahan lumbung Uluwatu tersebut ?

**Comment by tuanpembual** [comment]
Silahkan dishare
```
[Sekilat Info untuk Pengguna BlankOn Linux]

Hallo Pengguna BlankOn!

Ada kabar terbaru nih dari Tim Pengembang BlankOn. Saat ini lumbung (Repository) BlankOn Uluwatu sudah kembali mengudara. Lumbung BlankOn Uluwatu sempat tidak dapat diakses beberapa waktu lalu dikarenakan kerusakan sistem dan perangkat keras.

Alamat lumbung masih dilayani pada tautan yang sama; http://arsip.blankonlinux.or.id/blankon/dists/uluwatu/

Tim pengembang membutuhkan beberapa waktu, mulai dari perbaikan sistem, perangkat keras, pengujian lumbung hingga bisa kembali digunakan oleh pengguna BlankOn Linux Uluwatu.

Jejak tiket terkait permasalahan ini dapat dilihat bersama pada halaman :
https://github.com/BlankOn/Verbeek/issues/147

Merdeka untuk perangkat lunak terbuka, Terima kasih.

Salam,
Tim Pengembang BlankOn
```

**Comment by herpiko** [comment]
@tuanpembual 🚀

**Comment by slamets75** [comment]
- [ ] Telegram penguna BlankOn

- [ ] Twitter

- [ ] Milis BlankOn

- [ ] Instagram

- [ ] Facebook

**Comment by tuanpembual** [comment]
Mohon ini dilanjutkan woro2nya.
kalo sudah, silahkan ditutup.

**Comment by herpiko** [comment]
![Screenshot from 2020-12-08 13-11-08](https://user-images.githubusercontent.com/2534060/101487988-8d624180-3991-11eb-8071-cb1c90af2e0e.png)
Ini masih kurang karena uluwatu masih mengarah ke arsip-dev.

Pengguna perlu dipandu untuk mengarahkan ke arsip.boi alih-alih arsip-dev.

**Comment by herpiko** [comment]
Sudah disundul di twitter.

**Comment by aftian** [comment]
lumbung ini bagaimana cara buatnya? kok aneh

**Comment by herpiko** [comment]
@slamets75 @levay08 Untuk milis, instagram dan facebook ada yang bisa sodok? Supaya tiket ini bisa ditutup. IG dan FB saya ga bisa bantu karena ga punya akun.

**Comment by support-sttnf** [comment]
@herpiko Ok

**Comment by FaiqAminuddin** [comment]
Saya kirim ke FB
https://m.facebook.com/groups/blankonlinux/permalink/10158885009281602/

**Comment by slamets75** [comment]
Milis ✅
IG stories dan feed ✅

**Comment by samsulmaarif** [comment]
@slamets75 yang milis baru blankon-dev (pengembang) kah? yang blankon (milis pengguna) belum?
