### ISSUE TITLE
Rapat Koordinator 4 Desember 2020

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#175]
Pukul 20.00 WIB di https://meet.google.com/awu-apxq-cfg

Agenda bahasan:
- Laporan progres tim
- Blocker
- Komunikasi tim
- Lisensi dan pedoman perangkat lunak

**Comment by herpiko** [comment]
@raniaamina @slamets75 Timnya tidak lengkap, rapatnya dibatalkan. Silakan usulkan jadwal rapat pengganti, paling dekat besok, paling lama senin. 

Mohon kerja samanya.

**Comment by support-sttnf** [comment]
@herpiko Maaf, kelewat waktu.

besok jam 20.00

**Comment by raniaamina** [comment]
Saya usahakan besok, Pak.
Hari ini lagi kurang vit🙏
