### ISSUE TITLE
Kunjungan dan pamitan Waljinah

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#180]
Agenda:
- Kembalikan SSD aslinya
- Ambil SSD 128GB dan HDD 2TB
- Pamit

**Comment by herpiko** [comment]
Prioritas unggah ke mesin baru:
- /home
- Panduan

**Comment by herpiko** [comment]
SSD dan HDD waljinah sudah saya comot dan disimpan di republik bojong. Isinya akan segera saya unggah ke rafi.

SSD asli waljinah sudah saya kembalikan ke mesin dan mesin sudah saya kembalikan ke pihak weehost.

Penampakan terakhir waljinah sebelum pamitan.

![waljinah-farewell](https://user-images.githubusercontent.com/2534060/102617729-8f669600-4131-11eb-8779-4b6bc4f1cd1e.jpeg)

**Comment by herpiko** [comment]
Tiket lanjutan di https://github.com/BlankOn/Verbeek/issues/60

**Comment by herpiko** [comment]
SSD 128GB dan HDD 2TB saya simpan.

@samsulmaarif Direktori situs dari waljinah sudah diunggah ke rafi:/home/herpiko/situs

**Comment by samsulmaarif** [comment]
siap, terima kasih banyak pak @herpiko
