### ISSUE TITLE
Persiapan mesin baru dari pak Dhanank

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#181]

**Comment by samsulmaarif** [comment]
Mesin baru ini, nantinya akan menggunakan nama waljinah juga (karena pengganti) atau menggunakan nama baru (karena mesin baru) ya pak?

**Comment by herpiko** [comment]
@samsulmaarif Karena ganti mesin, mesti nama baru. Kita pamit sama Waljinah.

Usulan pak Estu, mesin baru akan dinamakan Rafi, untuk mengenang kawan kita yang sudah wafat. Saya pribadi akur.

**Comment by samsulmaarif** [comment]
Saya secara pribadi setuju dengan nama tersebut (Rafi), meskipun sepertinya itu mendobrak tradisi di BlankOn yang biasanya menggunakan nama-nama wanita Indonesia sebagai nama mesin.

**Comment by herpiko** [comment]
@tuanpembual mesinnya sudah bisa diserahterimakan ke tim infra? Untuk di:
- Daftarkan ke https://github.com/BlankOn/wiki/blob/master/TimPengembang/Infrastruktur/DaftarMesin.md
- Penyesuaian juru kunci https://github.com/BlankOn/wiki/blob/master/TimPengembang/JuruKunci.md
- Security hardening

**Comment by tuanpembual** [comment]
sundul @samsulmaarif

**Comment by samsulmaarif** [comment]
akhir pekan ini tim infra mau heketon pak @tuanpembual buat ngejar tiket-tiket infra yang tertunda

**Comment by herpiko** [comment]
https://github.com/BlankOn/Verbeek/issues/198

Per tiket di atas ditutup, saya rasa tiket ini bisa kita tutup. Terima kasih pak @samsulmaarif dan tim.
