### ISSUE TITLE
Kelas lanjutan Github dan Markdown untuk Tim Dokumentasi

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#182]

**Comment by herpiko** [comment]
Silakan diusulkan waktunya pak @FaiqAminuddin.

**Comment by FaiqAminuddin** [comment]
Bu @umulsidikoh dan pak @trisfaizal Sabtu malam pukul 20.00 siap?

**Comment by FaiqAminuddin** [comment]
Usulan materi;
Git
GitHub
Markdown
Pandoc

**Comment by umulsidikoh** [comment]
> Bu @umulsidikoh dan pak @trisfaizal Sabtu malam pukul 20.00 siap?

Siap, Pak.

**Comment by umulsidikoh** [comment]
> Bu @umulsidikoh dan pak @trisfaizal Sabtu malam pukul 20.00 siap?

Pak @FaiqAminuddin ini sabtu malam ini kan?

**Comment by herpiko** [comment]
@FaiqAminuddin Tiket ini perlu dicarikan dulu siapa pematerinya.

**Comment by somat** [comment]
https://github.com/somat/belajar-git

Saya coba cari waktu untuk menyampaikan materi ini secara daring.

**Comment by FaiqAminuddin** [comment]
> https://github.com/somat/belajar-git
> 
> Saya coba cari waktu untuk menyampaikan materi ini secara daring.

kami masih menunggu waktu luang pak @somat

**Comment by somat** [comment]
Oke pak, rencana hari Sabtu jam 19, atau hari Mingu jam 19, pilih salah satu.

Untuk memudahkan, bagi yang mau ikut silakan mengisi formulir ini ya pak:

https://forms.gle/TJQnm7bKNiQTttR9A

Rencana kelas dibagi beberapa sesi, setiap sesi maksimal 30 menit, supaya tidak terlalu lama.

**Comment by trisfaizal** [comment]
> Oke pak, rencana hari Sabtu jam 19, atau hari Mingu jam 19, pilih salah satu.
> 
> Untuk memudahkan, bagi yang mau ikut silakan mengisi formulir ini ya pak:
> 
> https://forms.gle/TJQnm7bKNiQTttR9A
> 
> Rencana kelas dibagi beberapa sesi, setiap sesi maksimal 30 menit, supaya tidak terlalu lama.

Hadir

**Comment by FaiqAminuddin** [comment]
@somat Tim dokumentasi memilih hari Minggu

**Comment by somat** [comment]
> @somat Tim dokumentasi memilih hari Minggu

Oke pak, hari Minggu, 10 Januari 2020, jam 19:00 kita jadwalkan untuk kelas git untuk pemula ya, kelasnya tidak lama-lama, supaya lebih efektif dan efisien.

**Comment by somat** [comment]
> @somat Tim dokumentasi memilih hari Minggu

Malam ini ya pak, jam 19, di google meet, link google meet nanti dikirimkan ke grup Telegram.
Harap standby 5 menit sebelum kelas dimulai.

**Comment by FaiqAminuddin** [comment]
@somat Siap

**Comment by somat** [comment]
Melanjutkan kelas git minggu lalu, jadwal berikutnya tanggal 17 Januari 2020 ya pak.
Untuk minggu ini kita jadwalkan jam 20;00 ya pak, biar gak bentrok sama isya'.

Minta tolong pak @aftian @samsulmaarif numpang google meet-nya ya pak biar bisa direkam.

**Comment by FaiqAminuddin** [comment]
Terim kasih pak @somat 
berikut saya setor tugas/PR pertemuan pertama
[https://github.com/bootcampgit/hellogitfaiq](https://github.com/bootcampgit/hellogitfaiq)

**Comment by trisfaizal** [comment]
Setor tugas Pak @somat 
Repo: https://github.com/ilumbung/hellogit-trisf/
PR: https://github.com/ilumbung/hellogit-trisf/pull/1

**Comment by samsulmaarif** [comment]
@somat sudah pak, di https://meet.google.com/awu-apxq-cfg silakan pak @FaiqAminuddin untuk mengundang peserta lainnya di google kalender

**Comment by somat** [comment]
Oke siap, terima kasih pak @FaiqAminuddin @trisfaizal ,
Terima kasih google meet-nya pak @samsulmaarif 

Sampai ketemu di kelas.

**Comment by umulsidikoh** [comment]
Pak @somat jika saya tidak salah lihat. Sepertinya Quiz 2 dari kelas git belum diperbaharui ya, Pak?

**Comment by somat** [comment]
> Pak @somat jika saya tidak salah lihat. Sepertinya Quiz 2 dari kelas git belum diperbaharui ya, Pak?

Wah iya, mohon maaf, lupa.
Sudah saya update ya di slide.

**Comment by umulsidikoh** [comment]
Setor tugas pak @somat 

Quiz 2. 
Tugas 1: https://github.com/umulsidikoh/kelasgit
Tugas 2: https://github.com/umulsidikoh/tugas-fork

Terima kasih.

**Comment by somat** [comment]
Tugas akhir untuk loka karya git:

1. Menulis menggunakan format markdown, di repo yang berkaitan dengan BlankOn
2. Submit pull request
3. Kirim link nya ke sini

**Comment by samsulmaarif** [comment]
@somat Halo Bapak/Ibu, berikut rekaman lokakarya Git & Markdown malam ini, Minggu, 24 Januari 2021 : https://drive.google.com/file/d/12wqWFgk8ZSCo3CRjUN8YnTHRdmWI6lGC/view?usp=sharing
