### ISSUE TITLE
Persiapan mesin baru kedua

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#183]
Dari NF.

Concern:
- Apa yang diharapkan dari kita (timbal balik)
- Apakah mesinnya secara fisik bisa diutak-atik (misal tambah HDD 4TB)

**Comment by samsulmaarif** [comment]
pak @slamets75 yang ini statusnya bagaimana ya dari NF?

**Comment by herpiko** [comment]
@slamets75 Ada update?
