### ISSUE TITLE
Alihkan arsip-dev.boi Menggunakan Nginx

### ISSUE THREAD

**Issue by samsulmaarif** [BlankOn/Verbeek#184]
Saat ini arsip-dev.boi masih dilayani oleh irgsh-go. Alihkan agar dilayani oleh nginx. 

Beberapa keuntungan menggunakan nginx antara lain:
- terdapat penanda waktu (timestamp) pada daftar berkas beserta ukurannya
- tidak tergantung pada service irgsh-go, jadi misal service irgsh sedang tidak berjalan arsip-dev.boi tetap bisa berfungsi
- keuntungan lain kita dapat menghidupkan repo uluwatu lama di arsip-dev.boi (dengan begini, harapannya bawaan instalasi uluwatu dapat langsung `apt update`)

langkah eksekusinya:
- [x] buat konfig nginx baru untuk arsip-dev di `/etc/nginx/sites-available`
- [x] aktifkan directory index
- [x] arahkan root ke `/var/www/irgsh-repo`
- [x] gunakan port 9001
- [x] arahkan envoy arsip-dev.boi ke port 9001

**Comment by samsulmaarif** [comment]
arsip-deb.boi sudah mengudara menggunakan nginx:

![Screenshot-20201205214946-708x249](https://user-images.githubusercontent.com/1231314/101246121-d8871500-3743-11eb-8470-ea6331f9c05d.png)

**Comment by herpiko** [comment]
![Screenshot from 2020-12-05 21-56-22](https://user-images.githubusercontent.com/2534060/101246268-c35eb600-3744-11eb-8919-4f3cae40908a.png)

Layanan arsip-dev.boi tetap hidup meskipun irgsh-repo dimatikan. Metadata juga sudah muncul sesuai ekspektasi.

Terima kasih pak @samsulmaarif .

**Comment by herpiko** [comment]
![Screenshot from 2020-12-05 22-47-10](https://user-images.githubusercontent.com/2534060/101247370-d7f27c80-374b-11eb-9a6d-eed1d50fadb9.png)


Pak @samsulmaarif moonmaap ini belom sip. Harusnya berkasnya terunduh bukan dirender begini. Ada header yang perlu disetel keknya di sisi nginx-nya.

**Comment by samsulmaarif** [comment]
@herpiko nitip dulu pak https://stackoverflow.com/questions/36804635/nginx-force-download-mp3-files

**Comment by samsulmaarif** [comment]
Sudah saya perbaiki pak @herpiko silakan dicoba kembali.

![image](https://user-images.githubusercontent.com/1231314/101321616-39276680-3898-11eb-80b2-163557d2372e.png)

**Comment by herpiko** [comment]
Sudah mantul jabrik. Terima kasih.
