### ISSUE TITLE
Jahitan: Pratinjau model keyboard tidak tampil pada Installer

### ISSUE THREAD

**Issue by leonyonz** [BlankOn/Verbeek#189]
# Melaporkan kutu

Kami menemukan kutu/masalah pada BlankOn Verbeek

 - Versi jahitan : 20201205-1

# Informasi Mesin:

- KVM
- 2vCPU
- 2GB RAM
- 20GB HDD
- UEFI

# Langkah Reproduksi

Masalah ini terjadi ketika melakukan pemilihan model keyboard pada installer

# Deskripsi masalah :

Pratinjau tata letak keyboard tidak tampil pada Installer

- Sampel Capture

![image](https://user-images.githubusercontent.com/42370275/101273735-a371d580-37ca-11eb-825b-dfbf2be1f214.png)

![image](https://user-images.githubusercontent.com/42370275/101273744-b389b500-37ca-11eb-93c0-651569de80bb.png)

# Ekspektasi

Pratinjau pada masing masing model keyboard tampil seperti pada jahitan [20201123-1](https://github.com/BlankOn/Verbeek/issues/143)

![image](https://user-images.githubusercontent.com/42370275/101273759-e469ea00-37ca-11eb-8e4a-319962f43589.png)

**Comment by aftian** [comment]
trims pak @herpiko setelah dipasang locales-all sudah keluar semua

**Comment by aftian** [comment]
trims pak @herpiko setelah dipasang locales-all sudah keluar semua
