### ISSUE TITLE
Jahitan: Gagal masuk grub setelah selesai instalasi dengan mode UEFI

### ISSUE THREAD

**Issue by leonyonz** [BlankOn/Verbeek#190]
# Melaporkan kutu

Kami menemukan kutu/masalah pada BlankOn Verbeek

 - Versi jahitan : 20201205-1

# Informasi Mesin:

- KVM & VirtualBox
- 2vCPU
- 2GB RAM
- 20GB HDD
- UEFI

# Langkah Reproduksi

Masalah ini terjadi ketika proses reboot paska instalasi selesai, detail langkah instalasi : [20201205-1.md](https://github.com/BlankOn/wiki/blob/master/TimPengembang/JaminanKualitas/UlasanJahitan/20201205-1.md)

# Deskripsi masalah :

Gagal masuk grub setelah selesai instalasi dengan mode UEFI

![image](https://user-images.githubusercontent.com/42370275/101274203-a2db3e00-37ce-11eb-84e2-52c1f4d8e074.png)

# Ekspektasi

Berhasil masuk grub dan booting ke OS.

**Comment by samsulmaarif** [comment]
[video] Gagal mencoba pasang ke komputer fisik dengan mode UEFI https://photos.app.goo.gl/QiGpBq8o2kSP4L4VA

**Comment by muhammad1505** [comment]
kayaknya emang belum support UEFI mas untuk versi sebelumnya juga belum support seingat saya

**Comment by herpiko** [comment]
Duplikat. Mohon dilanjutkan di https://github.com/BlankOn/Verbeek/issues/178
