### ISSUE TITLE
Periksa kelengkapan blankon.id sebelum dipublish/sebarluaskan

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#193]
- HTTPS (tunggu diterbitkan sama github)
- Cek halaman-halamannya
- Cek pranala
- Cek saltik di berita (blankon.id/berita.html)

Tunggu naik dulu (propagasi 24 jam)

**Comment by leonyonz** [comment]
Hi Pak @herpiko Terlampir hasil pengecekannya.

- HTTPS

![image](https://user-images.githubusercontent.com/42370275/101350601-cd59f380-38c1-11eb-9bb1-fc099b8e5749.png)

- Cek halaman Berita

![image](https://user-images.githubusercontent.com/42370275/101350634-dba80f80-38c1-11eb-85bc-395254b282b8.png)

![image](https://user-images.githubusercontent.com/42370275/101350683-f4b0c080-38c1-11eb-8ec5-faaaacb14078.png)

![image](https://user-images.githubusercontent.com/42370275/101350696-fc706500-38c1-11eb-84bf-fd3ec960397d.png)

- Cek saltik

CC: Pak @mdzulkifli @soewarsono @ricocwp

**Comment by herpiko** [comment]
@leonyonz Kesimpulan pengecekannya bagaimana pak? Apakah sudah ok untuk kita tinggalkan?

**Comment by leonyonz** [comment]
Sudah Oke Pak,
Tiket bisa diclose
