### ISSUE TITLE
paketkan blankon-gksu-configuration

### ISSUE THREAD

**Issue by hahn** [BlankOn/Verbeek#201]
https://github.com/blankon-packages/blankon-gksu-configuration

**Comment by artemtech** [comment]
kita masih perlu gksu kah?
soalnya udah lama di drop dari upstream,

https://jeremy.bicha.net/2018/04/18/gksu-removed-from-ubuntu/

**Comment by hahn** [comment]
wah berarti harus didrop juga dari blankon-desktop ya.

**Comment by herpiko** [comment]
@hahn Mohon dicatat di tiket meta pemaketan.

**Comment by hahn** [comment]
@herpiko siap pak

**Comment by herpiko** [comment]
Akan dihapus di https://github.com/BlankOn/Verbeek/issues/159
