### ISSUE TITLE
Wawancara kilas balik dengan pengembang lama episode 1

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#207]
Rekaman zoom/gmeet 2 partisipan. Skill/kemampuan yang bisa dicapai dari sini:
- Jurnalistik
- Video editing

Perlu:
- Siapa yang sikat
- Siapa yang diwawancarai

**Comment by herpiko** [comment]
Daftar ~interogasi~ pertanyaan:

- Pengalaman pertama bersentuhan dengan proyek
- Ada siapa saja waktu itu?
- Tim pertama
- Tantangan/hambatan terbesar
- Pencapaian terbesar
- Kemampuan yang diperoleh 
- Suka duka
- Pesan, saran, harapan untuk generasi baru

**Comment by FaiqAminuddin** [comment]
@herpiko Saya ingin wawancara pak mahadev

**Comment by samsulmaarif** [comment]
Akan saya coba untuk berkirim surel ke pak Utian, untuk menanyakan kesediaan beliau. Nanti saya cc ya pak @herpiko

**Comment by herpiko** [comment]
@samsulmaarif Terima kasih pak.

**Comment by samsulmaarif** [comment]
Pak @herpiko pak Utian bersedia Senin, 21 Desember 2020 pukul 19:30 s.d. 21:00 WIB. cc pak @yht

**Comment by herpiko** [comment]
@samsulmaarif Pak @yhtwebid, mau konfirmais lagi pak, akun zoom bapak bisa record on cloud?

**Comment by samsulmaarif** [comment]
Bapak/Ibu pendekar, apakah ada yang mau nitip pertanyaan untuk pak Utian nanti malam? Silakan ketik di sini ya, terima kasih.

**Comment by FaiqAminuddin** [comment]
@samsulmaarif Salah satu tujuan BlankOn adalah pengembangan SDM terutama yang para pengembanhnya. lalu apa keuntungan yang bisa didapatkan oleh pengguna BlankOn?

Sebagai orang yang sudah sangat mahir IT, apa motivasi Bapak selama jadi pengembang BlankOn? 

Sehubungan dengan keberadaan YPLI yang sudah tidak aktif, apakah diperlukan lembaga formal berbadan hukum untuk menaungi organisasi BlankOn ataukah cukup BlankOn sebagai komunitas saja? 

Sekarang jumlah pengembang BlankOn tidak banyak sehingga kadang terasa hanya beberapa orang saja yang aktif. 

Menurut Bapak, bagaimana cara menjaga kekompakan antara pengembang dan menarik pengembang baru?

**Comment by slamets75** [comment]
@FaiqAminuddin Bekal humas BlankOn di Era Digital ?
Bekal apa yang perlu disiapkan, kompetensi atau keahlian apa yang perlu dimiliki ?

**Comment by slamets75** [comment]
Saya ingin wawancara Pak Ainul dan Pak Rus mungkin Episode 3 & 4.

apa diperkenankan Pak Bapak ?
setelah dapat jawaban saya akan buat tiket.

**Comment by samsulmaarif** [comment]
@slamets75 episode 2 jadi pak @FaiqAminuddin ? langsung bikin tiket baru aja pak kalo jadi

**Comment by FaiqAminuddin** [comment]
@samsulmaarif saya ingin nonton dulu yang episode pertama

**Comment by herpiko** [comment]
Terima kasih banyak pak @samsulmaarif pak @yht.

Sudah naik, https://www.youtube.com/watch?v=-6SdHhybgzY

@slamets75  Silakan disodok,
- [ ] Twitter
- [ ] Facebook page
- [ ] Facebook group
- [ ] Instagram
- [ ] Milis dev
- [ ] Milis pengguna

**Comment by herpiko** [comment]
@slamets75 @levay08 Ini jadi disodok ke sosmed pabapak? Keburu kedaluarsa kelamaan.

**Comment by slamets75** [comment]
@herpiko Siap Pak.
Dicoba hari ini.

**Comment by slamets75** [comment]
[Sekilas Info] 
 
Hallo Pengguna BlankOn! 
 
Ada kabar terbaru nih, saat ini Tim Pengembang punya program yang diberi nama "Wawancara kilas balik dengan pengembang lama".

Pada Episode 1 Tim Pengembang BlankOn bersama Pak Utian Ayuba berbicara tentang pengalaman dan harapan untuk Pengembang BlankOn saat ini.

Silahkan saksikan #seri1 yang dapat diputar pada halaman ini: https://youtu.be/-6SdHhybgzYm

"Belajar dari pengalaman orang lain yang lebih dulu dan lebih tua akan membantu Kita melangkah lebih pasti."

Kutipan di atas mungkin menjadi awal pertimbangan kami untuk memulai program ini, semoga dapat mengispirasi.

Salam, 
Tim Pengembang BlankOn

**Comment by yht** [comment]
> Pak @herpiko pak Utian bersedia Senin, 21 Desember 2020 pukul 19:30 s.d. 21:00 WIB. cc pak @yht

Done.
Remove from cloud.

**Comment by herpiko** [comment]
Terima kasih pak @yht .

Terima kasih juga pak @slamets75. Tiket ini saya tutup.
