### ISSUE TITLE
Hidupkan panduan.blankon.id di Rafi

### ISSUE THREAD

**Issue by samsulmaarif** [BlankOn/Verbeek#214]
Tiket turunan dari #60 

## Daftar tugas
- [x] Gunakan berkas cadangan dari waljinah, file & database.sql (jika sudah ada)
- [x] Naikkan versi WordPress ke versi terkini (eksekusi dengan Docker)
- [x] Tidak lagi menggunakan SSO
- [x] Buat docker-compose.yml
  - [x] bisa gunakan wordpress docker image yang official atau build docker image sendiri
  - [x] mount bind `wp-content` ke direktori di host
  - [x] gunakan database mariadb
- [x] buat virtualhost panduan.blankon.id di nginx di host
- [x] Aktifkan SSL
- [x] buat redirect dari panduan.boi -> panduan.blankon.id

**Comment by samsulmaarif** [comment]
Ada usulan tema WordPress yang akan digunakan? 

Wacana lain sebenarnya sempat disinggung akan dialihkan ke Markdown, ada saran?

**Comment by herpiko** [comment]
Janjian sabtu malam besok pukul 19.00 untuk ulik bareng SSD waljinah. @herpiko @samsulmaarif

**Comment by herpiko** [comment]
Basis data mentah mysql dan postgresql di SSD waljinah sudah diangkut pak @samsulmaarif ke rafi.

**Comment by samsulmaarif** [comment]
Database `wppanduan` sudah saya dump di rafi, lokasinya ada di `/home/situs/backup/wppanduan.sql`

**Comment by kudaliar032** [comment]
Pak @samsulmaarif mau konfirmasi, untuk deployment dijadikan satu di direktori `/home/deployment` atau tetap di `/home/situs` saja?

**Comment by samsulmaarif** [comment]
@kudaliar032 @kudaliar032 pake /home/situs/ itu tradisi lama sih

**Comment by kudaliar032** [comment]
Pak @samsulmaarif, minta tolong untuk pointing kan domain `panduan.boi` dan `panduan.blankon.id` ke `rafi`.

**Comment by kudaliar032** [comment]
Pak @samsulmaarif, situs https://panduan.blankon.id sudah mengudara, silahkan ditinjau apakah sudah sesuai dengan daftar tugas. Terima kasih

**[Hasil tes SSL Labs](https://www.ssllabs.com/ssltest/analyze.html?d=panduan.blankon.id)**  

![hasil test ssl labs](https://i.imgur.com/rGh9SLj.png)

**Comment by herpiko** [comment]
@FaiqAminuddin Tiket turunan yang memungkinkan:

- Hubungi pak Iwan untuk kemungkinan keberlanjutan sponsor untuk sayembara panduan.

**Comment by FaiqAminuddin** [comment]
> @FaiqAminuddin Tiket turunan yang memungkinkan:
> 
>     * Hubungi pak Iwan untuk kemungkinan keberlanjutan sponsor untuk sayembara panduan.

tiket turunan saya buat di #247

**Comment by samsulmaarif** [comment]
pak @kudaliar032 Saran dari saya, sementara fitur register di website panduan dinonaktifkan dulu. Menghindari hal-hal yang tidak diperlukan terjadi.

**Comment by kudaliar032** [comment]
Baik pak @samsulmaarif, sudah saya nonaktifkan fitur registernya.

**Comment by samsulmaarif** [comment]
mantap, thanks dit @kudaliar032 tiket saya tutup karena tugas sudah selesai.

**Comment by herpiko** [comment]
Saya buka lagi tiketnya. Barusan 
![Screenshot from 2021-02-19 13-24-05](https://user-images.githubusercontent.com/2534060/108510756-ce8ea000-72b6-11eb-98e1-adc18a2ff0eb.png)

**Comment by samsulmaarif** [comment]
Sudah diperbaiki:

![image](https://user-images.githubusercontent.com/1231314/108531666-864c9d80-7309-11eb-9310-5671c05b8f86.png)
