### ISSUE TITLE
Buat kelompok video di kanal yutub

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#219]
- Rapat, semua yang terkait rapat masuk ke sini
- Lokakarya, semua yang terkait lokakarya masuk ke sini
- Kilas Balik, semua episode kilas balik masuk sini

**Comment by slamets75** [comment]
@herpiko Kita sebut ini daftar putar (playlist).

Jika kategori pada YouTube sudah ditentukan oleh sistem YouTube sendiri.

E.g Education, Science and Technology

**Comment by slamets75** [comment]
Playlist sudah dibuat dan video terkait sudah dikelompokkan.

- [x] Rapat
- [x] Lokakarya
- [x] Kilas Balik

**Comment by slamets75** [comment]
**Daftar putar kanal YouTube BlankOn**

![photo_2020-12-23_00-23-49](https://user-images.githubusercontent.com/22762466/102916255-d350f680-44b5-11eb-9de0-c38871742d22.jpg))

https://www.youtube.com/channel/UCY1wW-gCLS6SmgluGGFCqjw/playlists

**Comment by slamets75** [comment]
Nama YouTube BlankOn Linux sudah diubah menjadi **BlankOn**

Teringat kata ini tempo dulu oleh Pak @herpiko 
BlankOn -> Nama Proyek
BlankOn Linux -> Nama Produk

*) sebisa mungkin pakai nama yang sesuai jika tidak tersedia ya apa boleh buat.

![photo_2020-12-23_00-35-08](https://user-images.githubusercontent.com/22762466/102916808-bc5ed400-44b6-11eb-8ef7-49deaa176f39.jpg)

**Comment by herpiko** [comment]
Terima kasih banya bapak @slamets75 .
