### ISSUE TITLE
 Wawancara kilas balik dengan pengembang lama episode 2

### ISSUE THREAD

**Issue by FaiqAminuddin** [BlankOn/Verbeek#220]
**Nara sumber: Pak Aftian**
Pewawancara : Faiq (Dokumentasi)

minta tolong dibantu persiapan;
- [ ] Room dan Perekam : Pak @samsulmaarif dan Pak @yht 
- [x] Mohon pak @slamets75 (humas) menghubungi pak Aftian . Jadwal wawancara saya mengikuti nara sumber atau hari dan jam sama dengan episode 1
- [ ] Bapak ibu yang ingin titip pertanyaan bisa ditulis di sini sebagai bahan acuan wawancara yang akan disusun oleh tim dokukmentasi.

**Usul**
- [ ] sebelum diunggah, hasil rekaman bisa disunting oleh pak @raniaamina (kesenian) atau pak @herpiko

**Comment by slamets75** [comment]
@FaiqAminuddin Siap Pak, pakai pola dari email wawancara sebelumnya yang dikirim pak @samsulmaarif saja ya.

**Comment by raniaamina** [comment]
@FaiqAminuddin Akur

**Comment by slamets75** [comment]
Pola email sudah saya sesuaikan dan ditujukan ke Pak Rahman Yusri Aftian.

**Comment by slamets75** [comment]
sudah kontak dan kirim email ke Pak Rahman Yusri Aftian.

**Comment by FaiqAminuddin** [comment]
@slamets75 Terima kasih

**Comment by slamets75** [comment]
Usulan waktu Rabu, 08:00 - 09:00 sudah disampaikan kepada Pak Aftian dan beliau menyetujui.

**Comment by slamets75** [comment]
Pak @samsulmaarif minta usul kiranya mau pakai gmeet atau zoom ?

**Comment by FaiqAminuddin** [comment]
Wawancara kita rencanakan besok Rabu, 30 Desember 2020 jam 08.00 -- 09.00 WIB (masih menunggu konfirmasi nara sumber)

## Rancangan/panduan wawancara 
- Menurut Pak Aftian, BlankOn itu apa? Apa yang menarik dari BlankOn?
- Siapa sih penggagas atau pendiri BlankOn?

- Ada yang bilang, latang belakang pak Aftian bukan IT, kok tertarik dengan BlankOn?
- Menurut Bapak, siapa sih yang cocok jadi pengembang BlankOn?
- Kapan Bapak mulai bergabung dengan BlankOn? 
- Apa motivasi dan tujuan Bapak bergabung dengan BlankOn?
- Ada siapa siapa saja saat itu? Apakah banyak yang aktif atau banyak yang keluar masuk?

- Apa tantangan dan hambatan yang dihadapi pengembang BlankOn saat itu?
- Apa manfaat dan keuntungan yang Bapak rasakan saat jadi pengembang BlankOn?
- Apa suka duka jadi pengembang BlankOn?
- Menurut Bapak, Bagaimana kondisi BlankOn saat itu?
- Apakah keterlibatan Bapak dan tim pengembang di BlankOn berpengaruh dengan kegiatan di pekerjaan atau profesi bapak sehari-hari.
- Menurut Bapak, bagaimana cara menjaga kekompakan antara pengembang dan menarik pengembang baru?

- Apakah Bapak setuju dengan adanya istilah pensiunan BlankOn?
- Mengapa sekarang terlihat lebih aktif lagi dalam BlankOn
- Pesan, saran, harapan dan untuk pengembang BlankOn Verbeek?
- Apa kelebihan BlankOn yang dulu dengan yang sekarang?
- Apa kekurangan BlankOn yang dulu dan perlu dikejar pada BlankOn sekarang.

### Bapak dan Ibu yang ingin menitipkan pertanyaan untuk pak Aftian, dapat ditulis di tiket ini.

**Comment by samsulmaarif** [comment]
@slamets75 bebas sih, kalo hasil akhirnya sama menurut saya gmeet juga cukup, dengan catatan pewawancara dan yang diwawancara menyalakan kamera semua

**Comment by slamets75** [comment]
@samsulmaarif Rabu, 30 Desember 2020
Pukul : 08.00 - 09.00 WIB

Room : Google Meet - https://meet.google.com/asx-pcjd-ujb

Koordinasi dengan Pak @FaiqAminuddin selaku Pewawancara beliau sudah peggang akun tersebut.

**Comment by FaiqAminuddin** [comment]
Alhamdulillah wawancara sudah selesai.
rekaman dapat diakses di https://drive.google.com/file/d/1ppu9ANzB0UiBlzzYFQH6BGRWB2414BOe/view?usp=sharing
Semoga bermanfaat. Selanjutnya, silakan pak @raniaamina dan Tim Kesenian untuk mengolahnya sehingga lebih nyaman ditonton.

**Comment by slamets75** [comment]
@FaiqAminuddin Terima kasih Pak @FaiqAminuddin sudah menjalankan tugas dengan baik.

**Comment by raniaamina** [comment]
Ike pak, target tayang tanggal berapa?

**Comment by FaiqAminuddin** [comment]
> Oke pak, target tayang tanggal berapa?

Menurut saya, kalau bisa sebelum 6 Januari 2021

**Comment by herpiko** [comment]
@FaiqAminuddin Terima kasih pak @FaiqAminuddin pak @aftian 🙏
