### ISSUE TITLE
Hidupkan kembali konf*.boi

### ISSUE THREAD

**Issue by samsulmaarif** [BlankOn/Verbeek#222]
Tiket turunan dari #60 

konf.boi merupakan halaman yang menggambarkan atau menceritakan bahwa di BlankOn pernah digelar acara konferensi tahunan untuk pengembang, pengguna, dan pemerhati proyek BlankOn Linux. Telah digelar sebanyak 3 kali, yaitu pada tahun 2010, 2011, dan 2012. 

Nah, menurut teman-teman pengembang apakah halaman ini perlu dihidupkan? 

Diketahui bahwa laman tersebut dibangun menggunakan django dengan python 2.6. Tantangan untuk menghidupkan laman-laman tersebut antara lain:

- [x] menggunakan python 2.6 yang mana versi tersebut sudah sangat usang, 
- [x] ada kemungkinan ketergantungan (dependency) dari versi django dan python-nya sudah tidak bisa diunduh dengan mekanisme standar (pip misalnya)
- [x] belum diketahui versi django yang digunakan pada saat itu (belum ditemukan catatannya)
- [x] ada 2 pilihan cara untuk menghidupkan laman-laman tersebut, 
    - [x] 1. hidupkan di dalam kontainer (docker)
    - [x] 2. konversikan ke laman statis (meski sebenarnya kita tetap perlu menghidupkan laman tersebut terlebih dahulu dengan python & django, lalu kemudian bari bisa kita konversi ke versi statis, entah itu dengan httrack atau lainnya)

Daftar laman:
- [x] 1. konf.blankonlinux.or.id | redirect ke konf.blankon.id
- [x] 2. konf2010.blankonlinux.or.id | redirect ke konf2010.blankon.id
- [x] 3. konf2011.blankonlinux.or.id | redirect ke konf2011.blankon.id
- [x] 4. konf2012.blankonlinux.or.id | redirect ke konf2012.blankon.id

**Comment by herpiko** [comment]
@samsulmaarif Menurut saya bisa diskip dulu. Kita fokus dengan layanan yang akan/benar-benar kita pakai saja. Tapi semuanya boleh ditiketkan supaya nanti-nanti bisa kita kunjungi lagi untuk disikat kalau sudah waktunya.

**Comment by samsulmaarif** [comment]
siap pak @herpiko

**Comment by kudaliar032** [comment]
Laman sudah bisa dijalankan dengan bantuan docker, berikutnya konversikan laman ke dalam bentuk static site.

- [ ] konf.blankon.id
- [ ] konf2010.blankon.id
- [ ] konf2011.blankon.id
- [ ] konf2012.blankon.id

**Comment by kudaliar032** [comment]
Pak @samsulmaarif, minta tolong poitingkan domain berikut ke server rafi:

- [ ] konf.blankon.id
- [ ] konf2010.blankon.id
- [ ] konf2011.blankon.id
- [ ] konf2012.blankon.id

**Comment by samsulmaarif** [comment]
@kudaliar032 Done

**Comment by kudaliar032** [comment]
Lama sudah mengudara, dengan tautan:

- https://konf.blankon.id
- https://konf2010.blankon.id
- https://konf2011.blankon.id
- https://konf2012.blankon.id

Silahkan ditinjau pak @samsulmaarif :pray:

**Comment by samsulmaarif** [comment]
Sudah oke, tiket saya tutup. Terima kasih pak @kudaliar032.
