### ISSUE TITLE
Menyunting Video Kilas Balik 

### ISSUE THREAD

**Issue by raniaamina** [BlankOn/Verbeek#224]

**Comment by raniaamina** [comment]
Pak @herpiko @slamets75 @FaiqAminuddin ini rekaman kilas balik kurang sip, kalau dipaksa munculin videonya bisaa-bisa aja sih tapi nggak maksimal. Opsi lain, saya gosok jadiin semacam video podcast kalau diiizinkan. Dengan demikian saya maksimalin di penyuntingan audionya dulu.

**Comment by herpiko** [comment]
@raniaamina Kurang sipnya apa saja pak? Bisa didetailkan supaya jadi masukan untuk episode berikutnya?

**Comment by raniaamina** [comment]
1. Kualitas video 720p tapi terasa seperti 480p
2. Warna latar pak @FaiqAminuddin sama dengan bajunya, jadinya kalau diperbaiki warnanya kurang bisa maksimal
3. Video dari pak Aftian juga terlalu dekat dan sering keluar fokus saat bicara
4. Latar suara banyak noise/bising, bising dari sekitar dan perangkat

**Comment by herpiko** [comment]
@raniaamina Cc Bu @umulsidikoh Pak @senyumslamet untuk diperhatikan di video berikutnya.

@raniaamina saya akur kalau bapak mau jadikan audio podcast, bagaimana yang lain?

**Comment by FaiqAminuddin** [comment]
@herpiko Says juga aku.

Dan mohon maaf

**Comment by raniaamina** [comment]
Done, silakan dicek, pak bapak.

https://drive.google.com/file/d/1tlODb3w62aXs95tnXg7Ijx6HpCuIdohV/view?usp=sharing

**Comment by FaiqAminuddin** [comment]
Tiket ini saya tutup.
terima kasih pak @raniaamina  dan tim kesenian
selanjutnya silakan pak @slamets75 dan tim humas untuk menguploadnya di kanal BlankOn Linux

**Comment by slamets75** [comment]
@raniaamina upload ke kanal youtube sudah selesai.

https://youtu.be/3dTYkBQ-rv4
