### ISSUE TITLE
Rapat Koordinator Jumat 8 Januari 2021 Pukul 20.00 WIB

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#225]

**Comment by herpiko** [comment]
Ini kok desember.

Mari, https://meet.google.com/awu-apxq-cfg

**Comment by raniaamina** [comment]
@herpiko belum bisa move on jarinya

**Comment by samsulmaarif** [comment]
Rapat sudah dilaksanakan. Tiket saya tutup.
