### ISSUE TITLE
Jalin komunikasi lagi dengan Datautama

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#226]
Agenda bahasan:
- Sponsorship
- Tawaran colocation dengan potongan apakah masih berlaku

**Comment by samsulmaarif** [comment]
Halo pak @slamets75 kalo ada pembaruan bisa diketik di tiket ini ya pak. Terima kasih. :pray: :pray: :pray:

**Comment by samsulmaarif** [comment]
Tiket dilanjutkan di #250, tiket ini saya tutup.
