### ISSUE TITLE
SMU internship

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#227]
Yang perlu dipikirin:
- Tugas dan deliverables-nya apa.
- Perlu digaji ga sih?
- Mentornya siapa
- Dampak ke tim gimana (apakah ntar switch ke bahasa inggris sampai waktu tertentu)

**Comment by herpiko** [comment]
Rapat pada Selasa, 19 Januari 2020, 19.00 WIB di Gmeet. cc @slamets75 @tuanpembual .

**Comment by tuanpembual** [comment]
saya prefer menolak tawarn SMU.
karena beban full internship agak berat dgn budaya kerja opensource yg kita anut.

**Comment by herpiko** [comment]
Kesimpulan ngobrol barusan:

Sementara difollow up dulu sama pak @slamets75 , kalau jadi ketemuan isinya palingan:

- Intro dari kita
- Tanya berapa orang yang magang
- Tepatnya berapa lama magangnya (di surel 3 bulanan)
- Background dari anak magang gimana, CS semua atau gimana
- Bahas poin keberatan di atas mengenai budaya kerja FLOSS
- Bahas

Kelar dari sini diputuskan, kita angkut apa tidak.

**Comment by samsulmaarif** [comment]
pak @slamets75 maaf boleh tau ini apakah sudah ada hasil _follow up_-nya?

**Comment by slamets75** [comment]
@samsulmaarif belum ada pak @samsulmaarif

**Comment by samsulmaarif** [comment]
Oke pak @slamets75 kita tutup saja tiket ini ya pak, anggap sudah kadaluarsa tawarannya. Karena menurut pengalaman saya tawaran seperti ini hanya berlaku selama 2 Minggu.

**Comment by slamets75** [comment]
@samsulmaarif Ok baik Pak
