### ISSUE TITLE
Wawancara kilas balik dengan pengembang lama episode 4 

### ISSUE THREAD

**Issue by umulsidikoh** [BlankOn/Verbeek#234]
**Narasumber : Pak Rusmanto**
Pewawancara : Umul Sidikoh (Tim Dokumentasi)

Beberapa hal yang perlu dipersiapkan, diantaranya:

- [x] Materi/bahan pertanyaan
- [x] Menghubungi narasumber
- [x] Room online: oleh pak @yht atau pak @samsulmaarif 
- [x] Pertanyaan titipan dari pengembang lain (jika ada)

**Usul**
Sebelum diunggah, hasil wawancara disunting oleh tim kesenian cc pak @raniaamina

**Comment by raniaamina** [comment]
Mohon dikondisikan dan disadari bahwa obrolan direkam, jadi pastikan audio dan video aman. Untuk opsi alternatif, saya sarankan ada yg rekam manual, misal via OBS alih-alih mengandalkan rekaman baku dari Gmeet.

**Comment by umulsidikoh** [comment]
> Mohon dikondisikan dan disadari bahwa obrolan direkam, jadi pastikan audio dan video aman. Untuk opsi alternatif, saya sarankan ada yg rekam manual, misal via OBS alih-alih mengandalkan rekaman baku dari Gmeet.

Siap, saya usahakan video dan audio aman. Terima kasih sarannya, Pak.

**Comment by umulsidikoh** [comment]
Saya sudah menghubungi Pak Rusmanto melalui surel dan japri telegram. Jika tidak ada kendala, wawancara kilas balik eps 4 dilaksanakan pada hari Sabtu, 23 Januari 2021 Pukul 20.00 WIB. Mohon kiranya pak @samsulmaarif saya minta tolong dibuatkan room meeting untuk proses wawancara dengan beliau. Terima kasih!

**Comment by umulsidikoh** [comment]
Jika pak-bapak ada pertanyaan titipan untuk Pak Rus. Bisa diinfokan ke saya ya.

**Comment by samsulmaarif** [comment]
> Mohon dikondisikan dan disadari bahwa obrolan direkam, jadi pastikan audio dan video aman. Untuk opsi alternatif, saya sarankan ada yg rekam manual, misal via OBS alih-alih mengandalkan rekaman baku dari Gmeet.

pak @raniaamina bersedia untuk merekam menggunakan OBS? 

> Jika pak-bapak ada pertanyaan titipan untuk Pak Rus. Bisa diinfokan ke saya ya.

bu @umulsidikoh Saya titip pertanyaan yang pernah diajukan oleh pak @FaiqAminuddin di episode 1 yang tidak saya tanyakan ke pak Utian, menurut saya lebih relevan jika pertanyaan berikut ditanyakan ke pak Rusmanto:

> Sehubungan dengan keberadaan YPLI yang sudah tidak aktif, apakah diperlukan lembaga formal berbadan hukum untuk menaungi organisasi BlankOn ataukah cukup BlankOn sebagai komunitas saja?

> Sekarang jumlah pengembang BlankOn tidak banyak sehingga kadang terasa hanya beberapa orang saja yang aktif.
> Menurut Bapak, bagaimana cara menjaga kekompakan antara pengembang dan menarik pengembang baru?

Ruangannya bisa menggunakan https://meet.google.com/awu-apxq-cfg, sudah saya buatkan event di kalender, silakan bu @umulsidikoh cek email/google kalender, lalu undang email pak Rusmanto ke acara tersebut di kalender.

**Comment by umulsidikoh** [comment]
Baik. Segera saya catat pertanyaan tambahannya, Pak @samsulmaarif dan terima kasih atas gmeetnya.
Jika memungkinkan, saya coba untuk merekam menggunakan OBS, Pak.

**Comment by umulsidikoh** [comment]
Rekaman Wawancara Kilas Balik Pengembang Eps #4 dengan Pak Rusmanto bisa dicomot disini ya pak-bapak: https://drive.google.com/drive/folders/1_Nd1AJyEJZJvKSdf0lbBxSaufA_BLs0e?usp=sharing

Terima kasih!

**Comment by samsulmaarif** [comment]
@umulsidikoh Berikut rekaman versi gmeet : https://drive.google.com/file/d/1G76YnAUIIBVwPpWpXnRIZBTjrsale8QO/view?usp=sharing

**Comment by umulsidikoh** [comment]
Mungkin bisa dieksekusi pak-bapak yg lain, hasil rekamannya. cc @raniaamina

**Comment by raniaamina** [comment]
@umulsidikoh Oke, belum bisa ngedit cepet. Lagi ada task ngedit dari sebelah. Pak @Nuggrungeho @bajinra bisa bantu handle?

**Comment by ikinugrihi** [comment]
Hasil editing bisa di cek di link berikut 

https://drive.google.com/file/d/1cBi_eJtKfmIckIFtS8OWlClcY2rqIfj_/view?usp=sharing

**Comment by slamets75** [comment]
@ikinugrihi Ijin sundul ke youtube

**Comment by umulsidikoh** [comment]
Pak @slamets75 ini video sudah diunggah ke yutub?

**Comment by samsulmaarif** [comment]
Tiket saya tututp karena sudah dilaksanakan, video juga sudah naik di youtube. --> https://www.youtube.com/watch?v=YTrQ-a8M7tQ
