### ISSUE TITLE
Lokakarya/sharing mengenai clean architecture di Golang

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#235]
Waktu: Rabu, 20 Januari 2020, 19.00 WIB
Tempat: Gmeet dari pak @samsulmaarif 
Pengisi materi: Pak @wejick

**Comment by samsulmaarif** [comment]
@herpiko URL gmeet https://meet.google.com/awu-apxq-cfg

**Comment by samsulmaarif** [comment]
Sudah ditunggu pak @wejick bapak/ibu -> https://meet.google.com/awu-apxq-cfg

**Comment by samsulmaarif** [comment]
Halo Bapak/Ibu pendekar BlankOn, berikut adalah rekaman lokakarya Clean Architecture di Golang : https://drive.google.com/file/d/1-1plb0sX1CqgcL2R9DNEUQZSdmkIWUmP/view?usp=sharing

Tiket saya tutup karena sudah dilaksanakan.
