### ISSUE TITLE
Installer masih ada logo debian

### ISSUE THREAD

**Issue by aftian** [BlankOn/Verbeek#238]
Kami menemukan kutu/masalah pada BlankOn Verbeek  
  
- Versi jahitan : 2021016-1
  
# Informasi Mesin:  
  
Jenis mesin:  virtual (kvm)
Spesifikasi mesin:
- CPU: 2
- RAM: 4
- Diska: 15
  
# Langkah Reproduksi  
  
Masalah ini terjadi ketika melakukan installasi dan masih muncul logo debian

https://github.com/blankon-packages/calamares-settings-blankon/tree/master/calamares/branding/blankon

- welcome
- slide1

Mohon kesenian dan pemaket untuk diperhatikan

  
# Deskripsi masalah :  muncul logo debian

**Comment by herpiko** [comment]
@raniaamina Bisa dibantu bikinkan asetnya pak? Bapak bisa cobain jahitan untuk lebih dapat gambarannya. Lebih spesifik, ada 2 berkas yang perlu dipoles asetnya, sesuai deskripsi tiket.

**Comment by raniaamina** [comment]
![slide-1](https://user-images.githubusercontent.com/22146607/105441109-7013d900-5c9a-11eb-833c-ee728f4c6af6.png)

![welcome](https://user-images.githubusercontent.com/22146607/105441113-71dd9c80-5c9a-11eb-8bd2-61d87cc01172.png)

bisa dicoba pak

**Comment by herpiko** [comment]
@raniaamina Tampiasih. 🙏

**Comment by herpiko** [comment]
Sudah diangkut di https://github.com/blankon-packages/calamares-settings-blankon/pull/2.

**Comment by herpiko** [comment]
https://github.com/blankon-packages/calamares-settings-blankon/blob/master/calamares/branding/blankon/blankon-logo.png

@raniaamina logo ini memungkinkan gambar latarnya diganti sedikit ke warna #2c3133 pak? Jadi lebih menyatu dengan latar di belakang. Saat ini penampakannya seperti ini:

![Screenshot from 2021-04-13 18-53-53](https://user-images.githubusercontent.com/2534060/114605658-d6047100-9c89-11eb-82c7-fd3aa6aaaee5.png)

**Comment by raniaamina** [comment]
Memungkinkan pak @herpiko

**Comment by raniaamina** [comment]
![blankon-logo](https://user-images.githubusercontent.com/22146607/115997253-b7e52c00-a60c-11eb-91e6-0f9128923ff8.png)
