### ISSUE TITLE
Setel pipeline dan deployment khusus untuk E2E testing irgsh

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#240]
Usul numpang dulu di rafi.boi. Barangkali ini kesempatan buat tim infra untuk kenal irgsh yang baru lebih jauh dengan merakit deploymentnya dari awal sampai persis seperti irgsh.boi yang sekarang.

**Comment by samsulmaarif** [comment]
Sepertinya agar tidak mengganggu sistem yang berjalan ke depannya, kita perlu buatkan VM di dalam rafi.boi ya pak. Deployment irgsh di dalam VM tersebut.

**Comment by herpiko** [comment]
@samsulmaarif Akur dan manut.

**Comment by samsulmaarif** [comment]
Tugas yang perlu dieksekusi untuk tiket ini:

- [ ] Aktifkan KVM di rafi
- [ ] buat VM dengan OS debian 10
- [ ] deploy irgsh di dalam VM tersebut
- [ ] buat port forwarding di host agar VM dapat di akses dari luar
- [ ] buat pipeline job untuk deployment dari GA ke VM

**Comment by samsulmaarif** [comment]
akan dideploy di http://irgsh-dev.blankonlinux.or.id

**Comment by herpiko** [comment]
Kasus silang untuk e2e:
- Repo:
  - experimental
  - dev
- Jenis paket:
  - Paket native
  - Paket non-native dengan source git
  - Paket non-native dengan source tarball

**Comment by samsulmaarif** [comment]
`irgsh-repo sync` dalam proses di `irgsh-development`

![irgsh-devel-repo-sync-2021-04-14_05-18](https://user-images.githubusercontent.com/1231314/114633050-11cf2300-9cea-11eb-822a-26c1a7b6ca59.png)

**Comment by herpiko** [comment]
Ini perlu dicabut semua kecuali yang pull request (semua cabang)
https://github.com/BlankOn/irgsh-go/blob/master/.github/workflows/generic.yml#L6

**Comment by samsulmaarif** [comment]
Sudah saya cabut pak @herpiko
