### ISSUE TITLE
Bikin cron untuk trigger Github Action blankon-live-build

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#244]
Tiap hari jam 16.00 WIB dengan pertimbangan kelar magrib (2 jam) dan bisa ditengok bareng-bareng selepas magrib (pulang kerja/kuliah/sekolah(?)). 

Catatan untuk GA, di sisi antar muka, tombol `Re-run Jobs`-nya cuma keliatan di commit terakhir.

**Comment by kudaliar032** [comment]
Pak @herpiko, terkait tiket ini saya sudah kirimkan pull request berikut https://github.com/BlankOn/blankon-live-build/pull/18, mohon untuk ditinjau. Terima kasih

**Comment by samsulmaarif** [comment]
Pemicu sudah dibuat oleh @kudaliar032 dan sudah jalan. Tiket saya tutup.
