### ISSUE TITLE
Rani dan layanannya tidak dapat diakses

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#248]
### SSH
```
$ ssh piko@rani.blankonlinux.or.id
ssh: connect to host rani.blankonlinux.or.id port 22: Network is unreachable
```

### CURL
```
irgsh log
Fetching the logs of 2021-04-12-002635_40e20a1c-83ad-43fd-935e-e2cf8a094823_4E1C6A31FB1DF66463806857F73403755814255E_gnome-control-center ...
2021/04/12 06:40:20 main.go:823: Get "https://irgsh.blankonlinux.or.id/api/v1/status?uuid=2021-04-12-002635_40e20a1c-83ad-43fd-935e-e2cf8a094823_4E1C6A31FB1DF66463806857F73403755814255E_gnome-control-center": dial tcp 202.154.57.165:443: i/o timeout
```

**Comment by herpiko** [comment]
@samsulmaarif Tapi di sini katanya idup.

![Screenshot from 2021-04-12 06-48-11](https://user-images.githubusercontent.com/2534060/114351787-9d19ae80-9b5a-11eb-9883-daa1532ca06a.png)

**Comment by samsulmaarif** [comment]
@herpiko port ssh-nya sudah dicoba yang 2222 pak?

**Comment by herpiko** [comment]
@samsulmaarif Oiya bener, tapi sama.

```
$ ssh piko@rani.blankonlinux.or.id -p 2222
ssh: connect to host rani.blankonlinux.or.id port 2222: Network is unreachable
```

Mungkin bener kepentok dingap.

**Comment by samsulmaarif** [comment]
terkonfirmasi IP-nya pak piko masuk daftar block, sudah saya cabut dari daftar tersebut secara manual. Silakan dicoba lagi, jika sudah oke, tiket ini boleh ditutup.

**Comment by herpiko** [comment]
Sudah tocker kembali. Terima kasih banyak selangit.
