### ISSUE TITLE
Pasang tema colormag ke panduan.blankon.id

### ISSUE THREAD

**Issue by samsulmaarif** [BlankOn/Verbeek#249]
- [x] Kloning/backup db & data panduan.blankon.id
- [x] Pasang tema colormag
- [x] Rapikan, kalau bisa didampingi tim Dokumentasi

**Comment by FaiqAminuddin** [comment]
![Uploading image.png…]()


Judul tulisan pada slider tidak jelas bila gambarnya berwarna putih atau cerah

**Comment by samsulmaarif** [comment]
> Uploading image.png…

ini gambarnya belum selesai diunggah pak @FaiqAminuddin
