### ISSUE TITLE
Koordinasi Data Utama Server Colocation- Server Alynne BlankOn Dev

### ISSUE THREAD

**Issue by slamets75** [BlankOn/Verbeek#250]
Komunikasi dengan Bu Myke dari Data Utama dan memberikan detail Server.

Spesifikasi : https://docs.google.com/document/d/1xwgXUUY7VJOkJDLqCJpIy8JdBFd9mmXufJOEVs5XS1s/edit?usp=sharing

Kebutuhan : penempatan colocation

**Comment by samsulmaarif** [comment]
pak @slamets75 saya mau tanya, apakah pihak Data Utama menanyakan/meminta proposal sponsorship? Terima kasih.

**Comment by slamets75** [comment]
@slamets75 Kebutuhan Internet berapa Mbps ?
Butuh IP Publik ?

Pertanyaan dari Bu Myke.

**Comment by samsulmaarif** [comment]
Butuh donk pak @slamets75

**Comment by samsulmaarif** [comment]
pak @slamets75 tiket ini saya tutup karena kita jadinya pake https://netzen.net.id/ untuk colocation ya.
