### ISSUE TITLE
Rapat Mingguan 18 April 2021

### ISSUE THREAD

**Issue by samsulmaarif** [BlankOn/Verbeek#251]

**Comment by slamets75** [comment]
**Catatan Rapat BlankOn**

Milestone Rilis Alpha 1 digeser menjadi 29 April 2021.

Tim Humas
- Data Utama keputusan sponsor akan difollowup kembali senin 19 April 2021.
- Distro watch dan Debian census kontak ulang dengan email resmi humas blankon.

Tim Jaminan Kualitas
- Proses gagal dan terdapat galat (Boost.python ...)
- Laporan pengujian clamares. #tanggapan
perlu ditambahkan spesifikasi mesin pengujian.
- Menghapus layanan tempel yang sudah tidak digunakan.
- Istilah BlankOn Installer menjadi Clamares.

Tim Dokumentasi
- Web panduan sudah dipasang template baru.
- Sponsor siap memberikan hadiah untuk program sayembara.
- Lokakarya untuk tim dokumentasi untuk mengelola web panduan.blankon.id

Tim Kesenian
- Persiapan desain rilis (poster, wallpaper, 
- Wallpaper Ok dari Pak Nugroho.

Tim Pemaket
- Kendala paket wallpaper di irgsh #tanggapan sudah dilakukan perbaikan oleh Pak @herpiko 
- Menanyakan kembali komitmen tim pemaket.
- Usulan terkait pengecekan dan kebutuhan pemaket
[--experimental --ignore-checks] hanya berlaku pada experimental tidak pada dev.

Tim Infra
- Menunggu kabar selanjurnya persiapan rilis alpha (1).

Manajer Rilis
- Fokus membantu tim pemaket.
- Pemaketan GRUB.

Harapan semua tim bisa membantu menguji, memberikan masukan tiket.
Rapat seminggu sekali untuk persiapan rilis.
Rapat selanjutnya minggu, 25 April 2021.
