### ISSUE TITLE
Layanan HTTP di rani yang melayani directory listing 

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#252]
Untuk naruh berkas-berkas random lewat scp terus bisa ditarik dari mana pun via http. Misal taroh di /mnt/public terus kaitkan ke gudang.blankonlinux.or.id.

Tujuannya nanti mau saya pakai buat naruh blob yang akan ditarik sama end to end test irgsh.

**Comment by samsulmaarif** [comment]
Pak @kudaliar032 mohon bantu sikat ini yak. Terima kasih.

**Comment by kudaliar032** [comment]
Sudah saya tambahkan konfigurasinya pak @samsulmaarif, untuk direktorinya saya arahkan ke `/mnt/public` dengan tautan `http://gudang.blankonlinux.or.id`. Mohon arahkan domain tersebut ke server rani, terima kasih :pray:

**Comment by samsulmaarif** [comment]
Beres 

![](https://i.imgur.com/hGoZVoj.png)

Tinggan nunggu propagansi.
