### ISSUE TITLE
Berita Rilis Alpha-1 Versi Pengembangan

### ISSUE THREAD

**Issue by slamets75** [BlankOn/Verbeek#257]
Berita rilis alpha-1 versi pengembangan dikirimkan ke kanal BlankOn diantaranya:

- [x] Telegram Pengguna
- [x] Instagram
- [ ] Twitter
- [x] Facebook
- [x] Milis Pengembang
- [x] Milis Pengguna

**Comment by slamets75** [comment]
![Blankon Verbeek Rilis Alpha 1](https://user-images.githubusercontent.com/22762466/116511513-bfe4ea80-a8f0-11eb-95e8-3389e4863f1a.png)

**[Kabar BlankOn Versi Alpha-1 | Rilis Pengembangan]**

Tepat pada hari ke-17 Ramadhan tahun 1442 H atau bertepatan dengan tanggal 29 April 2021 M, kami para pengembang BlankOn, secara resmi meluncurkan rilis Alpha-1.

Unduh gratis di:
https://s.klas.or.id/BlankOn12-Alpha1

Pada rilis ini pengembang BlankOn hanya meluncurkan untuk arsitektur amd64 versi pengembangan yang ditujukan untuk pengujian dan pengguna ahli. Karena merupakan versi pengembangan, masih akan ditemukan banyak kutu untuk diperbaiki pada rilis pengembangan versi berikutnya.

Laporan pengujian bisa dikirimkan:
lapor.blankon.id

Berita rilis selengkapnya dapat dikunjungi pada halaman berikut:
https://blankon.id/berita/2021/04/29/catatan-rilis-blankon-12-alpha-1.html

Yuk berkontribusi!

Salam
**Koordinator Humas BlankOn**

**Comment by slamets75** [comment]
> Berita rilis alpha-1 versi pengembangan dikirimkan ke kanal BlankOn diantaranya:
> 
> * [x]  Telegram Pengguna
> * [x]  Instagram
> * [ ]  Twitter
> * [x]  Facebook
> * [x]  Milis Pengembang
> * [x]  Milis Pengguna

Semua sudah terdistribusikan.

**Comment by samsulmaarif** [comment]
@slamets75 Makasih pak @slamet75

**Comment by slamets75** [comment]
sama-sama Pak @samsulmaarif
