### ISSUE TITLE
Infrastruktur Monitoring

### ISSUE THREAD

**Issue by samsulmaarif** [BlankOn/Verbeek#258]
Untuk memantau penggunaan sumber daya infrastruktur mesin yang digunakan oleh Proyek BlankOn diperlukan sebuah alat monitoring. Saat ini sudah ada nms.blankon.id yang sudah terpasang LibreNMS.

Tambahkan mesin-mesin berikut ke dalam librenms dengan protokol snmp:

- [x] Rani
- [x] alynne
- [x] rafi
- [x] batasi akses port dengan dingap

**Comment by kudaliar032** [comment]
Ini `nms.blankon.id` terpasang dimesin mana ya pak @samsulmaarif? Dan apakah bisa saya minta kunci aksesnya?

**Comment by kudaliar032** [comment]
Pak @samsulmaarif, ini sepertinya ada miss di konfigurasinya, apakah memungkinkan untuk akses server monitoringnya?

![](https://i.imgur.com/VySaq0g.png)

**Comment by kudaliar032** [comment]
Pak @samsulmaarif untuk monitoring sudah di pasang pada mesin rafi menggunakan [Observium](https://www.observium.org/). Minta tolong disiapkan untuk domainnya kemaren saya konfigurasi sementara pakai `monitroing.blankonlinux.or.id` bisa pakai itu atau mungkin ada saran lain untuk domain lainnya? Terima kasih

**Comment by samsulmaarif** [comment]
oke pak @kudaliar032 domain sudah saya pointing, terima kasih.

**Comment by kudaliar032** [comment]
Untuk monitoring sudah saya tambahkan ke daftar [Domain dan Layanan](https://github.com/BlankOn/wiki/blob/master/TimPengembang/Infrastruktur/DomainDanLayanan.md), untuk juru kunci layanan tersebut juga sudah saya tambahkan ke [Juru Kunci](https://github.com/BlankOn/wiki/blob/master/TimPengembang/JuruKunci.md). Jika dirasa sudah cukup tiketnya boleh ditutup pak @samsulmaarif :pray:

**Comment by samsulmaarif** [comment]
okay dit, tiket saya tutup.
