### ISSUE TITLE
Domain www.blankonlinux.or.id tidak menampilkan situs yang benar

### ISSUE THREAD

**Issue by kudaliar032** [BlankOn/Verbeek#264]
## Deskripsi ringkas

Terdapat laporan bahwa domain www.blankonlinux.or.id tidak menampilkan situs yang benar

## Hal yang diharapkan

Domain menampilkan situs web blankon

![image](https://user-images.githubusercontent.com/23249302/119214187-748cb900-baf7-11eb-8c06-27e8a80d9ac6.png)

## Hal yang terjadi

![image](https://user-images.githubusercontent.com/23249302/119214226-c2092600-baf7-11eb-9d1d-a779530e88ac.png)

## Apakah hal ini selalu terjadi? (Ya/Tidak)

Ya

**Comment by kudaliar032** [comment]
## Sidik Gangguan

- Domain tidak menampilkan situs yang benar dikarenakan belum terdapat konfigurasi yang menangani domain tersebut pada web service sehingga menampilkan halaman default [rafi.boi](https://rafi.blankonlinux.or.id)
- Solusi yang dilakukan yaitu menambahkan konfigurasi untuk mengalihkan [www.blankonlinux.or.id](https://www.blankonlinux.or.id) ke [blankon.id](https://blankon.id)

Mohon kiranya bantuan dari Tim JK untuk memvalidasi tiket ini dan menutupnya jika dirasa sudah sesuai. cc: @mdzulkifli @leonyonz @soewarsono @ricocwp. Terima kasih

**Comment by leonyonz** [comment]
Dicoba akses sudah redirect ya : 

![image](https://user-images.githubusercontent.com/42370275/119330563-86658c00-bcb0-11eb-8ec5-3926fbf0a630.png)

Ijin closed case
