### ISSUE TITLE
Masa Depan BlankON Linux

### ISSUE THREAD

**Issue by BlueCore-lab** [BlankOn/Verbeek#267]
Apakah BlankON Linux akan tetap selamanya menggunakan GNOME sebagai UI dan Debian GNU/Linux sebagai basisnya?

**Comment by herpiko** [comment]
@BlueCore-lab Tidak selamanya, itu tergantung keputusan tim yang memelihara distribusi ini. Dalam waktu dekat tidak ada perubahan terkait GNOME dan Debian.
