### ISSUE TITLE
Publikasi sponsorship Netzen

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#275]
- [x] Kabar berita (blog post)
- [x] Facebook
- [x] Twitter
- [x] IG
- [x] Milis
- [x] Xbanner fisik

**Comment by FaiqAminuddin** [comment]
@slamets75 apakah tidak tertulis di MoU? kalau di rancangannya yang belum ada ttdnya tertulis: 
1. PIHAK PERTAMA bersedia menjadi sponsor PIHAK KEDUA dalam penyelenggaraan proyek BlankOn sebagai Sponsor PETA LEVEL.

**Comment by FaiqAminuddin** [comment]
rancangan berita saya pull request di https://github.com/BlankOn/beranda/pulls

**Comment by herpiko** [comment]
@slamets75 Sudah bisa ditutup? Mintul dicentang checkboxnya di deskripsi tiket.

**Comment by slamets75** [comment]
Checkbox sudah disesuaikan 

- [x] Kabar Berita (post)
- [x] IG
- [x] FB
- [x] Twitter
