### ISSUE TITLE
BlankOn on ILC 2022

### ISSUE THREAD

**Issue by slamets75** [BlankOn/Verbeek#281]
Komunitas BlankOn dalam acara community _dinner and gathering_  Indonesia Linux Conference (ILC) 2022

**Comment by slamets75** [comment]
Tim pengembang BlankOn yang turut hadir:
1. @raniaamina 
2. @soewarsono 
3. @samsulmaarif 
4. @somat 
5. @slamets75 
6. @artemtech 
...

**Comment by slamets75** [comment]
mohon bantuannya Pak @somat untuk buatkan berita dan konten untuk agenda keikutsertaan kita sebagai pengisi dalam kelas paralel & sesi komunitas.

**Comment by slamets75** [comment]
Membuat laporan keikutsertaan BlankOn sebagai komunitas di acara ILC 2022.

**Comment by slamets75** [comment]
![image](https://user-images.githubusercontent.com/22762466/205498889-028c944d-9f17-4a20-be5d-11887682ff7b.png)

**Comment by FaiqAminuddin** [comment]
Racangan berita tentang ILC

**ILC, BlankOn dan Secangkir Semangat**
Setelah hampir 10 tahun tidak dilaksanakan, ILC kembali dilaksanakan pada 5 November 2022. Sebagaimana diumumkan di ilc.opensuse.id, ILC  2022 ini merupakan bentuk inisiatif dari komunitas-komunitas open source di Indonesia untuk kembali memulai kegiatan langsung pasca-pandemi COVID-19. ILC tahun ini akan mengusung konsep acara yang lebih kasual, fun, dan tentunya tetap edukatif untuk setiap partisipan yang terlibat di dalamnya.

Beberapa komunitas yang terlibat langsung sebagai Tim ILC 2022 antara lain; Komunitas Gimpscape Indonesia, Kelompok Linux Arek Suroboyo (KLAS), openSUSE ID, dan KPLI Bogor. Selain itu ada beberapa komunitas yang menjadi mitra, termasuk BlankOn. Beberapa pengembang BlankOn juga terlibat (atas nama pribadi atau komunitas yang lain) sebagai panitia, pemateri dan peserta.

Menurut tim humas BlankOn, setelah kegiatan ILC 2022, ada peningkatan pesan masuk ke email dan akun medsos humas. Ada yang menawarkan kerjasama dan ada yang minat bergabung menjadi pengembang BlankOn. Oleh karena itu kegiatan pengembangan BlankOn Verbeek juga terasa lebih bersemangat. Setidaknya rapat pengembang secara daring kembali diaktifkan secara rutin.

Semoga tahun 2023, kita dapat berkumpul lagi di ILC dan atau BlanKonf. : )

Monggo pak @somat
