### ISSUE TITLE
Sosialisasi Pengembang BlankOn dengan IT Club Linux NF (STT-NF)

### ISSUE THREAD

**Issue by slamets75** [BlankOn/Verbeek#287]
Pihak IT Club Linux NF dari STT Nurul Fikri mengusulkan beberapa  tanggal yang sekiranya bisa Bapak Ibu ikuti untuk melakukan sosialisasi baik daring maupun luring.

1. Sabtu, 17 Desember 2022 (Malam, 20:00 - 21.00) 
2. Minggu, 18 Desember 2022 (Siang, 13.30 - 14.30)

**Comment by FaiqAminuddin** [comment]
Usul: diusahakan diselenggarakan secara luring tapi daringkan juga.

Pada tanggal Rab, 30 Nov 2022 17.38, Slamet Santoso <
***@***.***> menulis:

**Comment by slamets75** [comment]
Persiapan Acara Sosialisasi

1. Waktu
2. Siapa yang bisa hadir & pemateri mau siapa ?
3. Isi acara

**Comment by slamets75** [comment]
Minggu, 18 Desember 2022 (Siang, 13.30 - 14.30)

waktu yang kita pilih Pak @somat aman ya untuk dapat bergabung diagenda luring ?

**Comment by slamets75** [comment]
@slamets75 untuk agenda berikut bisa hadir Pak ?

**Comment by somat** [comment]
> Minggu, 18 Desember 2022 (Siang, 13.30 - 14.30)
> 
> waktu yang kita pilih Pak @somat aman ya untuk dapat bergabung diagenda luring ?

Baik pak, Insya Allah untuk tanggal tersebut bisa bergabung.
