### ISSUE TITLE
Pipeline live build putus

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#302]
Terakhir sukses 10 bulan yang lalu..

<img width="877" alt="Screen Shot 2023-01-10 at 20 53 55" src="https://user-images.githubusercontent.com/2534060/211569702-2c8acc28-f82b-4e95-9c58-1d8a51d6ad15.png">

**Comment by samsulmaarif** [comment]
siap pak @herpiko kayaknya terkait SSL yang kadaluarsa

**Comment by samsulmaarif** [comment]
pipeline sudah hijau
