### ISSUE TITLE
[ask via email] by pengguna BlankOn Uluwatu

### ISSUE THREAD

**Issue by slamets75** [BlankOn/Verbeek#41]
Selamat pagi  perkenalkan saya robby baru menggunakan blank on uluwatu di laptop saya axioo mybook 14.

Jujur saya baru menggunakan linux dan baru belajar, setelah instalasi kenapa touchpad saya tidak bisa digunakan ya? Kalau saya menggunakan mouse wireless bisa. 
Saya coba cari info dengan edit di terminal tetapi gagal semua.

Saya coba instal distro linux lain seperti elementary dan ubuntu ternyata juga tidak bisa terdeteksi atau tidak aktif touchpad saya.

Mohon bantuannya terkait dengan error di touchpad saya ini.
Terimakasih

Dikirim dari Meizu M6

**Comment by herpiko** [comment]
@slamets75 

Kalau perintah ini dijalankan di komputer bapak, keluarannya apa, pak?

``
$ xinput
``

**Comment by slamets75** [comment]
setelah jalankan perintah

$ xinput

munculnya virtual core pointer pak., saya lampirkan juga gambarnya.

**Comment by herpiko** [comment]
@slamets75 Kalau dibalas via surel kayaknya lampirannya gak nyampe.

**Comment by herpiko** [comment]
Saya coba instal distro linux lain seperti elementary dan ubuntu ternyata juga tidak bisa terdeteksi atau tidak aktif touchpad saya.

^ Baru baca kalimat ini. Kalau di sistem operasi yang bukan GNU/Linux, tidak bisa juga? Jengjangan memang touchpadnya yang malfungsi.

**Comment by slamets75** [comment]
baik saya balas email tersebut, 

ticket sudah bisa di close., terima kasih atas tanggapannya.
