### ISSUE TITLE
Setel CI irgsh

### ISSUE THREAD

**Issue by samsulmaarif** [BlankOn/Verbeek#59]
- [x] build
- [x] deploy to rani
- [x] deploy only from master branch

**Comment by herpiko** [comment]
@tuanpembual 

The CI part was done. https://github.com/BlankOn/irgsh-go/actions/runs/322486606

CD job(s):

- Deploy
  - on:
    - commit to master
  - tasks:
    - Send it to rani.boi
    - Turn of the services
    - Replace the binaries
    - Turn on the services

Use scp and ssh, set the newly generated SSH key in secrets settings.

Also change [the build command](https://github.com/BlankOn/irgsh-go/blob/master/.github/workflows/main.yml) to `make release`. It will pack the binaries, config, templates etc to `target/release.tar.gz`. This `release.tar.gz` should be the artifact.

**Comment by herpiko** [comment]
Matikan dan nyalakan layanan irgsh di rani:

```
sudo systemctl stop irgsh-chief
sudo systemctl stop irgsh-builder
sudo systemctl stop irgsh-repo

sudo systemctl start irgsh-chief
sudo systemctl start irgsh-builder
sudo systemctl start irgsh-repo
```

**Comment by herpiko** [comment]
Saya buka kembali untuk implementasi https://github.com/BlankOn/tendang

**Comment by herpiko** [comment]
Sudah aman dan nyambung kembali disertai identifikasi versi.

<img width="1440" alt="Screen Shot 2020-11-04 at 19 52 20" src="https://user-images.githubusercontent.com/2534060/98133959-ccaff500-1ef0-11eb-8379-b045e8227e5c.png">
<img width="1440" alt="Screen Shot 2020-11-04 at 19 52 32" src="https://user-images.githubusercontent.com/2534060/98133972-d5083000-1ef0-11eb-9310-1500ff0c3374.png">
<img width="760" alt="Screen Shot 2020-11-04 at 21 49 40" src="https://user-images.githubusercontent.com/2534060/98133994-dafe1100-1ef0-11eb-80ab-3ce8cb1d257f.png">
