### ISSUE TITLE
Perbaiki laman wiki (dev.blankonlinux.or.id)

### ISSUE THREAD

**Issue by samsulmaarif** [BlankOn/Verbeek#63]
Saat ini laman wiki blankon yang beralamat di (dev.blankonlinux.or.id) tampilannya berantakan karena ada perpindahan laman utama (blankonlinux.or.id) ke GitHub pages. 

- [ ] Implementasikan tema [Docsy Jekyll](https://vsoch.github.io/docsy-jekyll/)

**Comment by herpiko** [comment]
Sudah dimigrasikan ke Docusaurus.
