### ISSUE TITLE
Isu bawaan Docusaurus

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#68]
Lanjutan dari https://github.com/BlankOn/wiki/issues/111

Silakan dikumpulkan isu-isu yang muncul setelah migrasi ke docusaurus.

**Comment by FaiqAminuddin** [comment]
- [ ] perbaikan tautan **edit this page***

- [ ] perbaikan nama file (README) yang muncul di side bar

**Comment by FaiqAminuddin** [comment]
- [ ] glosarium masih macet 
- [ ] tampilan beberapa daftar menjadi semacam kutipan kode seperti pada https://dev.blankonlinux.or.id/TimPengembang/Humas/README
- [ ] menu Produk macet (https://dev.blankonlinux.or.id/ProdukBlankOn/README)

**Comment by FaiqAminuddin** [comment]
butuh Daftar isi atau indeks sebagai ganti daftar isi manual https://github.com/BlankOn/wiki/tree/master/DaftarIsi
sehingga pembaca awal dapat mengetahui acara

**Comment by herpiko** [comment]
Sesuai usulan @tuanpembual , yang terkait ke isu platform wiki tiketnya dipindahkan ke wiki. https://github.com/BlankOn/wiki/issues/123
