### ISSUE TITLE
Migrasi berkas unggahan / asset dari dev-legacy.boi ke dev.boi

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#71]
Pindahan dari https://github.com/BlankOn/Verbeek/issues/71

Seluruh lampiran sepertinya tertinggal di wiki trac. Perlu : 
- Direktori khusus aset
- Konvesi penamaan berkas aset.

Kendala:
- Perlu dicari tahu di mana trac hidup dan berkas deployment-nya ada di mana. Terakhir ada di dev-legacy.blankonlinux.or.id

**Comment by samsulmaarif** [comment]
Lampiran sudah ditambahkan di https://github.com/BlankOn/wiki/pull/117
