### ISSUE TITLE
Riset dan deploy lapor.boi

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#76]
- Skenario 1: Form -> GitHub -> Telegram dev
- Skenario 2: Form -> Telegram dev (decision making) -> GitHub issues

**Comment by raniaamina** [comment]
Mockup perdana untuk halaman LaporBOI!

![laporboi](https://user-images.githubusercontent.com/22146607/97007609-de49e200-156b-11eb-8d7a-a8fda94611f2.png)

**Comment by herpiko** [comment]
Canggih jabrik!

Saran:
- Tim BlankOn diganti menjadi tag (atau mungkin istilah lain), secara pengguna tidak serta merta mengassign issu ke tim tertentu. Kolom ini boleh tidak diisi karena pengguna mungkin tidak memiliki pengetahuan yang cukup atas hal tersebut. Ada pun isinya adalah sebagian dari Label yang ada di GitHub Issues, yakni:
  - Pemaketan
  - Infrastruktur
  - Kesenian
  - Riset
  - JaminanKualitas
  - Dokumentasi

@raniaamina Apakah sumber kodenya akan dirilis di bawah BlankOn? Jika iya, akan saya siapkan lumbung kodenya. Jika tidak, mohon nanti tempelkan tautan sumber kode untuk membuka kemungkinan kontribusi dari yang lain.

**Comment by raniaamina** [comment]
Itu sifatnya opsional, mesti ada pilihan general memang untuk bantu pengguna.

Sementara kode sumber akan disimpan di sini dulu:
https://github.com/artemtech/lapor-boi

**Comment by artemtech** [comment]
link demo:
https://lapor-boi.vercel.app/

fitur:
- kirim laporan ke telegram
- upload attachment

**Comment by herpiko** [comment]
Habisi!

**Comment by artemtech** [comment]
tinggal deployment

**Comment by somat** [comment]
Isian _form_ sebaiknya diberikan penanda isian yang wajib diisi, dan isian yang tidak wajib diisi. Misalnya menggunakan tanda bintang, dan diberi keterangan di bawahnya.

**Comment by leonyonz** [comment]
Hi Tim, 

Apakah sudah rilis ?

**Comment by herpiko** [comment]
Kepentok sama https://github.com/BlankOn/Verbeek/issues/74.

Tunggu beberapa waktu lagi, akan ada kabar baik dari sponsor.

**Comment by herpiko** [comment]
Sudah bisa dideploy ke rafi. @samsulmaarif Mohon disiapkan domain yang diarahkan ke mesin rafi.

**Comment by samsulmaarif** [comment]
@herpiko siap pak

**Comment by kudaliar032** [comment]
## Daftar pekerjaan untuk dieksekusi

- [ ] Buat domain dan diarahkan ke rafi
- [ ] Butuh kredensial untuk bot Telegram
- [ ] Pull kode di server
- [ ] Bangun dan jalankan layanan lapor.boi
- [ ] Konfigurasikan `https` di nginx

Untuk yang poin 1 dan 2 minta support ya pak @samsulmaarif

**Comment by samsulmaarif** [comment]
oke dit @kudaliar032

**Comment by samsulmaarif** [comment]
Domain sudah dipointing:

- [ ] lapor.blankon.id
- [ ] lapor.blankonlinux.or.id --> redirect ke lapor.blankon.id

**Comment by kudaliar032** [comment]
Pak @artemtech, untuk lapor-boi telah saya deploy. Untuk skup ujinya bagaimana?

cc: @leonyonz

**Comment by leonyonz** [comment]
Hadir Pak, siap nguji jika udah ada skupnya.

**Comment by artemtech** [comment]
skup uji laporboi v1

## Akses
- pastikan domain lapor.blankon.id bisa diakses dengan baik
- akses domain lapor.blankonlinux.or.id kalau memang dibikin redirect, berti harus bisa redirect dengan baik ke lapor.blankon.id
- akses domain harus https atau ndak ini? kalau https, pastikan bisa diakses melalui https://lapor.blankon.id,

## Penggunaan
### Bagian informasi laporan
- apakah informasi yang sudah tampil saat ini cukup memberikan informasi untuk pelaporan tiket?
- validasi yang *harus diisi* saat ini adalah nama, email, tipe laporan, fitur/layanan, cc ke tim apa.

### Bagian rincian laporan
- judul dan deskripsi adalah mutlak harus ada, pastikan kalo kosong, ndak mau dikirim
- lampiran bisa berupa sembarang berkas, sifatnya opsional (max size-nya belum diatur dari kode)
- format penulisan mengikuti markdown

### Bagian laporan terkini
- pastikan menampilkan tiket terkini sesuai issue di github berdasar 3 tiket teratas sortir berdasar tanggal.
- pastikan klik tiket bisa mengarahkan ke tiket terkait dengan benar.
- pastikan klik laporan lainnya mengarah ke url tiket proyek saat ini.

### Bagian informasi panduan pengisian
- apakah informasinya sudah cukup jelas untuk end-user?

### Mengirim laporan
- terdapat notifikasi bahwa tiket sedang dikirim
- terdapat notifikasi bahwa tiket gagal dikirim (jika gagal)
- terdapat notifikasi bahwa tiket berhasil dikirim
- apakah notifikasi pengiriman sudah cukup memberikan informasi terkait pengiriman?
- tiket yang dikirim dari platform ini akan diteruskan di channel telegram yang akan diproses sesuai [Skenario 2](https://github.com/BlankOn/Verbeek/issues/76#issue-727936713)
- kalau ada lampiran yang disertakan, harus bisa diangkut ke channel telegram juga

**Comment by leonyonz** [comment]
On check Pak

**Comment by leonyonz** [comment]
## Akses

![image](https://user-images.githubusercontent.com/42370275/102692926-65a09280-4249-11eb-8330-e93ccf69d3bb.png)

![image](https://user-images.githubusercontent.com/42370275/102692952-9385d700-4249-11eb-9536-884e87c90d3d.png)

![image](https://user-images.githubusercontent.com/42370275/102692941-7bae5300-4249-11eb-9c7c-a81385905d87.png)

**Catatan:** Sudah sesuai dengan ekspektasi

## Penggunaan

### Bagian informasi laporan

-   **apakah informasi yang sudah tampil saat ini cukup memberikan informasi untuk pelaporan tiket?**
**Jawab:** Dari saya sudah OK

-   **validasi yang _harus diisi_ saat ini adalah nama, email, tipe laporan, fitur/layanan, cc ke tim apa.**

![image](https://user-images.githubusercontent.com/42370275/102693017-0c852e80-424a-11eb-9732-472b2813908c.png)

**Catatan:** Wajib isi sudah sesuai dengan ekspektasi

### Bagian rincian laporan

-   **judul dan deskripsi adalah mutlak harus ada, pastikan kalo kosong, ndak mau dikirim**

![image](https://user-images.githubusercontent.com/42370275/102693102-abaa2600-424a-11eb-85e8-0ec342dac028.png)

**Catatan:** Apabila terdapat cache pada form pengisian lapor boi, maka saat tiket dikirimkan akan menghasilkan informasi null

![image](https://user-images.githubusercontent.com/42370275/102694265-6d186980-4252-11eb-80c1-28d62b83e533.png)
Cache pada form yang dimaksud adalah saat user sudah mengisikan form namun dilakukan refresh pada browser, nantinya isi form akan langsung timbul pada masing masing form, saat form dikirim maka akan menghasilkan informasi null.

-   **lampiran bisa berupa sembarang berkas, sifatnya opsional (max size-nya belum diatur dari kode)**

**Jawab:** Uji menggunakan PDF tidak terkirim, penggunaan berkas gambar terkirim namun tidak berhasil opentiket

-   **format penulisan mengikuti markdown**

**Jawab:** Notifikasi bot telegram sudah mengikuti markdown namun tiket belum berhasil dibuka melalui lapor boi, jadi belum bisa dipastikan

-   **pastikan juga, saat user masuk platform ini, sudah ada template yang mereka tinggal isi (ini template nya generic)**

![image](https://user-images.githubusercontent.com/42370275/102693546-08f3a680-424e-11eb-8ae2-39ed0d135384.png)

### Bagian laporan terkini

-   **pastikan menampilkan tiket terkini sesuai issue di github berdasar 3 tiket teratas sortir berdasar tanggal.**

**Lapor boi**

![image](https://user-images.githubusercontent.com/42370275/102693799-b1563a80-424f-11eb-9ae9-64ee8b2cd16d.png)

**Issue GitHub**

![image](https://user-images.githubusercontent.com/42370275/102693811-c03ced00-424f-11eb-9424-6a22fc531dd7.png)

-   **pastikan klik tiket bisa mengarahkan ke tiket terkait dengan benar.**

**Catatan:** Tiket tidak tampil pada halaman Issue

![image](https://user-images.githubusercontent.com/42370275/102693929-815b6700-4250-11eb-95a3-08be737a7431.png)

-   **pastikan klik laporan lainnya mengarah ke url tiket proyek saat ini.**

**Catatan:** Sudah sesuai dengan ekspektasi

### Bagian informasi panduan pengisian

-   apakah informasinya sudah cukup jelas untuk end-user?

**Jawab:** Sudah Oke dari saya

### Mengirim laporan

-   **terdapat notifikasi bahwa tiket sedang dikirim**

![image](https://user-images.githubusercontent.com/42370275/102693651-c67e9980-424e-11eb-8c73-9488eb60d043.png)

**Catatan:** Proses pengiriman laporan agak lama

-   **terdapat notifikasi bahwa tiket gagal dikirim (jika gagal)**

**Catatan:** Tidak ada notifikasi tiket gagal kirim

-   **terdapat notifikasi bahwa tiket berhasil dikirim**

![image](https://user-images.githubusercontent.com/42370275/102693861-2aee2880-4250-11eb-9f68-b41e301048a0.png)

-   **apakah notifikasi pengiriman sudah cukup memberikan informasi terkait pengiriman?**

**Catatan:** Notifikasi gagal kirim belum ditemui

-   **tiket yang dikirim dari platform ini akan diteruskan di channel telegram yang akan diproses sesuai** [Skenario 2](https://github.com/BlankOn/Verbeek/issues/76#issue-727936713)

**Catatan:** Sudah Sesuai dengan ekspektasi

-   **kalau ada lampiran yang disertakan, harus bisa diangkut ke channel telegram juga**

![image](https://user-images.githubusercontent.com/42370275/102693890-5244f580-4250-11eb-85ae-8b287e938ff4.png)

**Catatan**: Sudah sesuai ekspektasi

cc: @artemtech

**Comment by samsulmaarif** [comment]
Apakah tiket ini sudah cukup sesuai untuk ditutup pak @leonyonz?

**Comment by leonyonz** [comment]
Terakhir uji, dari form belum bisa submit ke tiket github Pak @samsulmaarif , apakah memang belum develop sampai situ ?

**Comment by samsulmaarif** [comment]
Setahu saya memang belum, coba kita colek pak Sofyan @artemtech

**Comment by artemtech** [comment]
memang belum sampai situ pak @leonyonz @samsulmaarif

**Comment by leonyonz** [comment]
Siap kalo gitu ijin di tutup, karena sudah sesuai ekspektasi
