### ISSUE TITLE
live-build

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#77]
Dokumentasi hulu: https://live-team.pages.debian.net/live-manual/html/live-manual/index.en.html

- `lb build` pertama makan waktu hampir 1 jam
- Berikutnya (dibantu tembolok) hanya 2-3 menit

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
[2020-10-23 18:32:28] lb source 

real	2m38.134s
user	0m45.167s
sys	0m9.197s
piko@rani:~/live-default$
```

**Comment by herpiko** [comment]
Perbandingan performa tengah malam.

Rani:
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
[2020-10-23 18:49:18] lb source

real    12m41.058s
user    7m23.069s
sys     0m40.494s
```

Alynne.
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
[2020-10-23 14:51:09] lb source

real    21m34.450s
user    10m29.752s
sys     0m51.900s
```

**Comment by herpiko** [comment]
Hasil jahitan dapat ditengok dimari, http://cdimage.blankonlinux.or.id/blankon/jahitan-harian/current/

**Comment by herpiko** [comment]
Konfigurasi akhir dengan repo verbeek https://github.com/BlankOn/live-build

**Comment by herpiko** [comment]
Contoh lain dengan penjelasan: https://github.com/nmilford/skyhook-base

**Comment by herpiko** [comment]
Latest build from salsa [build_master.zip](https://github.com/BlankOn/Verbeek/files/5467299/build_master.zip) (https://salsa.debian.org/live-team/live-build/-/pipelines/191043)

**Comment by herpiko** [comment]
Build ISO sukses pertama yang menggunakan repo murni verbeek:
![Screenshot from 2020-10-31 03-08-07](https://user-images.githubusercontent.com/2534060/97752825-5d6c8680-1b27-11eb-8e40-3a51a0b7f517.png)

- Repo konfig: https://github.com/BlankOn/blankon-live-build
- Repo lb teranyar (fork dari salsa): https://github.com/BlankOn/live-build

Reproducible steps:
- Pasang keyring dari https://github.com/BlankOn/Verbeek/issues/81
- Salin /usr/share/debootstrap/scripts/stretch ke /usr/share/debootstrap/scripts/verbeek, ganti string strech ke verbeek di berkas baru tersebut.
- Kloning repo konfig, lalu
  - sudo lb clean --purge
  - sudo lb build

**Comment by samsulmaarif** [comment]
halo pak @herpiko saya sedang mencoba untuk reproduksi live-build ini berdasarkan referensi yang ada di issue ini. Nah, pada berkas `/usr/share/debootstrap/scripts/verbeek` saya tidak menemukan string `stretch` di sana pak:

```
samsul@alynne-builder:~/blankon-live-build$ cat /usr/share/debootstrap/scripts/verbeek
mirror_style release
download_style apt
finddebs_style from-indices
variants - buildd fakechroot minbase
keyring /usr/share/keyrings/debian-archive-keyring.gpg

# include common settings
if [ -e "$DEBOOTSTRAP_DIR/scripts/debian-common" ]; then
 . "$DEBOOTSTRAP_DIR/scripts/debian-common"
elif [ -e /debootstrap/debian-common ]; then
 . /debootstrap/debian-common
elif [ -e "$DEBOOTSTRAP_DIR/debian-common" ]; then
 . "$DEBOOTSTRAP_DIR/debian-common"
else
 error 1 NOCOMMON "File not found: debian-common"
fi

```

dan setelah saya jalankan `sudo lb build` saya mendapatkan galat :

```
E: Release signed by unknown key (key id 713C17F912D124D4)
   The specified keyring /usr/share/keyrings/debian-archive-keyring.gpg may be incorrect or out of date.
   You can find the latest Debian release key at https://ftp-master.debian.org/keys.html
P: Begin unmounting filesystems...
P: Saving caches...
chroot: failed to run command ‘/usr/bin/env’: No such file or directory

```

**Comment by samsulmaarif** [comment]
Update: setelah saya coba mengubah baris berikut:

```
keyring /usr/share/keyrings/debian-archive-keyring.gpg
```

menjadi 


```
keyring /usr/share/keyrings/blankon-archive-keyring.gpg
```

galat barusan hilang.

**Comment by herpiko** [comment]
@samsulmaarif Ah iya betul pak. Terima kasih atas koreksinya.

Tapi berkas ISO hasil buildnya keliatan pak? Saya mau coba jahit resmi dulu.

**Comment by herpiko** [comment]
Konfig dan dokumentasi sudah saya perbarui di sini, https://github.com/BlankOn/blankon-live-build

Tiket ini saya tutup. Oprekan-oprekan lanjutan live-build bisa langsung ditendang ke lumbung kode di atas.
