### ISSUE TITLE
Beberapa pertanyaan yang masuk dari email Humas

### ISSUE THREAD

**Issue by slamets75** [BlankOn/Verbeek#78]
1. Alamat kantor tim pengembang blankon? 
2. Tim pengembang blankon dibawah naungan PT ataukah yayasan?
3. Jika seseorang secara individu menyumbang dana bagaimana dengan laporan keuangannya?
4. Sekolah SMK mengajak MoU

**Comment by herpiko** [comment]
@slamets75 Yang onoh.

**Comment by herpiko** [comment]
@slamets75 

1. alamat utama tidak ada, alamat pengembang berdasarkan masing-masing alamat rumah pengembang
2. awalnya di bawah  naungan YPLI, namun selang beberapa waktu menjadi independen. sehingga tidak dalam naungan YPLI atau lembaga apapun
3. sumabgan biasanya dirupakan saat ada event tertentu, laporannya mengikuti event tersebut, bisa juga menyumbang ke personal atau bikin sayembara untuk bug solving

Sumber: pak Haris.
