### ISSUE TITLE
Setel SMTP di alynne

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#79]
Dibutuhkan terutama untuk memberitahukan milis blankon-dev perihal terbitan berkas citra jahitan dan lainnya, alih-alih menggunakan sendgrid gratisan.

- [x] smtp server menggunakan postfix
- [x] ~~izinkan hanya alamat ip alynne & rani yang boleh menggunakan smtp server~~
- [x] ~~pengiriman dengan TLS~~

## Pastikan
- [x] email tidak masuk spam
- [x] skor terbaik di https://www.mail-tester.com

**Comment by kudaliar032** [comment]
![](https://i.imgur.com/YiiJMDd.png)

**Comment by herpiko** [comment]
@kudaliar032 ada contoh cara ngirim via curl?

**Comment by kudaliar032** [comment]
@herpiko Untuk pengirimannya pakai SMTP client pak, tidak ada API nya

**Comment by samsulmaarif** [comment]
Sudah menggunakan smtp relay dari Radnet.
