### ISSUE TITLE
Paket keyring verbeek

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#81]

**Comment by herpiko** [comment]
Skup uji:

- Pasang sid di vbox
- Pasang manual paket berikut dengan dpkg: http://rani.blankonlinux.or.id:8082/dev/pool/main/b/blankon-keyring/blankon-keyring_2020.10.29-1.0_all.deb
- Alihkan repo ke `http://rani.blankonlinux.or.id:8082/dev verbeek main restricted extras extras restricted`
- `apt update`
- `apt install` sembarang paket
- Ekspektasi: mulus tanpa galat tanda tangan digital.

**Comment by herpiko** [comment]
Latest build from salsa [build_master.zip](https://github.com/BlankOn/Verbeek/files/5467299/build_master.zip) (https://salsa.debian.org/live-team/live-build/-/pipelines/191043)

**Comment by herpiko** [comment]
Pak @hahn @antosamalona @ainandoo 

Sekarang irgsh bisa submit paket tanpa source, contoh (langsung dicoba saja nanti):

### 1. Perbarui irgsh-cli
```
curl -L -o- https://raw.githubusercontent.com/BlankOn/irgsh-go/master/install-cli.sh | bash
```

Pastikan dapat versi `202011231801` dengan perintah `irgsh-cli --version``, pastikan versi yang sama juga tercantum di induknya https://irgsh.blankonlinux.or.id

### 2. Dorong paket tanpa kode sumber

Misal paket `blankon-keyring`, pastikan bawa flag `--experimental`, 
```
irgsh-cli submit --experimental --package https://github.com/blankon-packages/blankon-keyring.git
```

Jika lancar mintul konfirm di https://github.com/BlankOn/irgsh-go/issues/78

**Comment by herpiko** [comment]
Masih kepentok https://github.com/BlankOn/Verbeek/issues/132

**Comment by antosamalona** [comment]
sama, pak

**Comment by hahn** [comment]
ini error yang sama kah pak @herpiko ?

```
Successfully signed dsc, buildinfo, changes files
Submission failed.
401 Unauthorized
```

**Comment by herpiko** [comment]
@hahn Ini karena kunci bapak belum didaftarkan ke irgsh. Kemarin hanya kunci yang ikut lokakarya yang didaftarkan. Silakan kirim kunci publik bapak kemari untuk didaftarkan ke irgsh.

**Comment by hahn** [comment]
[hanhan-husna-gpg.pub.txt](https://github.com/BlankOn/Verbeek/files/5594196/hanhan-husna-gpg.pub.txt)
Terima kasih pak

**Comment by antosamalona** [comment]
`After this operation, 397 kB of additional disk space will be used.
Err:1 http://kartolo.sby.datautama.net.id/debian sid/main amd64 libfakeroot amd64 1.25.3-1
  404  Not Found [IP: 123.255.202.74 80]
Err:2 http://kartolo.sby.datautama.net.id/debian sid/main amd64 fakeroot amd64 1.25.3-1
  404  Not Found [IP: 123.255.202.74 80]
E: Failed to fetch http://kartolo.sby.datautama.net.id/debian/pool/main/f/fakeroot/libfakeroot_1.25.3-1_amd64.deb  404  Not Found [IP: 123.255.202.74 80]
E: Failed to fetch http://kartolo.sby.datautama.net.id/debian/pool/main/f/fakeroot/fakeroot_1.25.3-1_amd64.deb  404  Not Found [IP: 123.255.202.74 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
I: Copying back the cached apt archive contents
I: unmounting dev/ptmx filesystem
I: unmounting dev/pts filesystem
I: unmounting dev/shm filesystem
I: unmounting proc filesystem
I: unmounting sys filesystem
I: cleaning the build env 
I: removing directory /var/cache/pbuilder/build/7 and its subdirectories

404 page not found
`

**Comment by samsulmaarif** [comment]
@antosamalona ini URLnya kalo diakses manual melalui peramban 404 juga sih http://kartolo.sby.datautama.net.id/debian/pool/main/f/fakeroot/fakeroot_1.25.3-1_amd64.deb

**Comment by antosamalona** [comment]
Iya, pak.

**Comment by herpiko** [comment]
@antosamalona Sudah bisa dicoba lagi pak.

1. Dorong di experimental dulu.
2. Kalau sukses di experimental, dorong ke dev.

**Comment by herpiko** [comment]
@antosamalona Sudah naik ya. Sudah keangkut juga ke ISO.

http://arsip-dev.blankonlinux.or.id/dev/pool/main/b/blankon-keyring/
