### ISSUE TITLE
Implementasi stunnel redis antara rani dan alynne.

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#82]
https://redislabs.com/blog/stunnel-secure-redis-ssl/

**Comment by herpiko** [comment]
![Uploading Screen Shot 2020-11-03 at 20.28.39.png…]()

**Comment by herpiko** [comment]
Perlu riset stunnel, output:
- docker-compose yang isinya
  - redis-a, 6371:6379
  - redis-b, 6371:6379
  - stunnel-a
  - stunnel-b
- self-signed cert yang dipakai sama stunnel
- Ekspektasi: client redis-a setor data key value, client redis-b bisa lihat data tsb.

Semua dilakukan di lokal. Semau petunjuk ada di tautan di deskripsi tiket

Kurleb macam ni.
<img width="990" alt="Screen Shot 2020-11-03 at 20 28 39" src="https://user-images.githubusercontent.com/2534060/98062764-38f31000-1e81-11eb-844d-891f82542e6b.png">

**Comment by misskecupbung** [comment]
Mohon direview pak https://github.com/misskecupbung/redis-stunnel-tls .

**Comment by herpiko** [comment]
Canggih bets. Saya coba dulu ya, Bu.

**Comment by tuanpembual** [comment]
ini berarti redisnya tidak termasuk di compose ini?

**Comment by misskecupbung** [comment]
Redis servernya nya ada di folder site-a pak,

**Comment by herpiko** [comment]
@misskecupbung Saya lihat sudah sip. Perbaikan minor barangkali:

- Sertifikat dan kunci jangan dibawa saat build (Dockerfile) tapi nyuntiknya lewat volume, supaya dibikin jadi lebih agnostik.

Saat tiket sedang dikerjakan, mohon digeser ke papan *in proggres*.

Pak @samsulmaarif mohon Bu Ananda diizinkan dan dibimbing untuk akses mesin/deploy ke rani dan alynne. Dalam konteks ini, rani adalah induk redisnya. Tidak harus dalam waktu dekat, disikat saat santai saja.

**Comment by tuanpembual** [comment]
maaf, saya masih belum paham.
ini artinya redis server hanya ada di rani/igrsh-builder?
sedang irgsh hanya menggunakan redis stunnel dari rani/irgsh-builder?
apakah begitu?

**Comment by herpiko** [comment]
@tuanpembual Kalau lihat dokumentasi stunnel, iya servernya di yang induk. Nanti jadinya berti (mohon dikoreksi):

```
irgsh-(chief/builder/repo) --- redis --- stunnel --------------------- stunnel --- irgsh-builder
```
Tujuannya di sini kita bisa nyalain builder di alynne yang berinduk ke irgsh di rani.
@misskecupbung @samsulmaarif Kita perlu bikin cert dengan CA seperti dulu lagi, kunci-kuncinya dipelihara dengan disiplin. Bisa merujuk ke panduan [di sini](https://gist.github.com/herpiko/c26e90d0f98e69ed159ed89d7dcc2486) (boleh dibawa ke wiki infra kalau mau). Bu Ananda bisa jadi kuncen.


```
 CA (exp: 10y)
  |
Intermediate CA (exp: 5y)
      |
   ____|__________________________
  |              |                |
RedisRani   RedisAlynne      CertKebutuhanLain
```

**Comment by tuanpembual** [comment]
mungkin, gambar sekalian diupdate.
ini kunci induk sudah pernah ada pak? (CA)

**Comment by herpiko** [comment]
@tuanpembual Tidak ada. Hangus sama irgsh v2 yang lama.

**Comment by herpiko** [comment]
@herpiko - CA, cn: BlankOnRootCA
- Intermediate, cn: BlankOnIntermediateCA
- Cert _turunan, cn: redis-stunne-rani, redis-stunnel-alynne, mesin-ini-itu, etc

Lainnya:
- C: ID
- ST: Jakarta
- L: Jakarta
- O: BlankOn
- U: BlankOn Infrastructure
- emailAddress: blankon-dev@googlegroups.com

**Comment by misskecupbung** [comment]
Baik pak @herpiko @tuanpembual . Nanti akan diperbaiki dan akan diupdate lagi, Terima kasih koreksinya.

**Comment by herpiko** [comment]
@misskecupbung Terima kasih. 👍

**Comment by tuanpembual** [comment]
Kudos!

**Comment by herpiko** [comment]
Pak @kudaliar032 jadi kudeta tiket ini?

**Comment by kudaliar032** [comment]
Jadi pak @herpiko

**Comment by herpiko** [comment]
@kudaliar032 🚀

**Comment by kudaliar032** [comment]
Pak @herpiko, untuk redis + stunnel sudah saya deploy di mesin `rani` dan `alynne`, monggo dicek pak. Untuk sertifikat CA juga sudah saya buat, kuncinya saat ini dipegang oleh saya dan pak @samsulmaarif.

**Comment by herpiko** [comment]
@kudaliar032 @kudaliar032 Mohon tambahkan bagian baru di halaman ini, misal CA, terus tempelkan CN CA yang dikelola, lalu nama dan surel bapak dan pak Samsul.

https://github.com/BlankOn/wiki/blob/master/TimPengembang/JuruKunci.md

**Comment by samsulmaarif** [comment]
Tiket saya tutup karena sudah diimplementasikan.
