### ISSUE TITLE
Kelas IRGSH dari perspektif juru kode (3 November 2020, 19.00 WIB)

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#86]

**Comment by herpiko** [comment]
- Tempat berkumpul: https://meet.google.com/erm-rgkz-fpy
- Agenda:
  - Diskusi/tanya jawab mengenai cara kerja detail irgsh
  - Review ringkas struktur kode
  - Contoh patch/tambalan

**Comment by samsulmaarif** [comment]
URL gmeet sudah diperbarui pak @herpiko

**Comment by herpiko** [comment]
Coretan draw.io:

[irgsh(1).drawio.zip](https://github.com/BlankOn/Verbeek/files/5481867/irgsh.1.drawio.zip)

**Comment by herpiko** [comment]
Ini sudah dilaksanakan, tiket ini saya tutup.
