### ISSUE TITLE
Setel CI/CD live build

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#87]
Gimana caranya supaya setiap ada pembaruan di lumbung ini atau Action-nya ditrigger manual, maka:

- Komit terakhir di lumbung ini dibawa ke rani /mnt/blankon-live-build
- Tendang build.sh

**Comment by samsulmaarif** [comment]
Monon maaf pak @herpiko "lumbung ini" itu mengacu ke mana ya pak?

**Comment by herpiko** [comment]
@samsulmaarif Yang ini https://github.com/BlankOn/live-build

**Comment by herpiko** [comment]
@samsulmaarif Maaf, yang ini maksudnya, https://github.com/BlankOn/blankon-live-build

**Comment by herpiko** [comment]
Tambah notif di build.sh-nya `blankon-live-build`, letakkan kredensial di .env

`curl smtp://redacted --mail-from redacted --mail-rcpt redacted--upload-file message.txt`

**Comment by herpiko** [comment]
Tendang lewat https://github.com/BlankOn/tendang

**Comment by herpiko** [comment]
```
curl --header "Content-Type: application/json" --request POST --data "{\"name\":\"isoworker\",\"value\":\""$VALUE"\", \"token\": \""$TOKEN"\"}" http://$HOST
```

VALUE punya pola `username_branch`. Pipeline yang dibikin ada 2:
- master, value-nya `blankon_master`
- pull request, value-nya `username_branch`

**Comment by herpiko** [comment]
Skup uji:
- Setelah pipeline selesai, nilai value-nya (segera cek) akan masuk ke `/mnt/blankon-live-build/QUEUE.txt`.
- Uji baik dengan pull request mau pun dorong ke master.

**Comment by herpiko** [comment]
Sudah ok. Trims.
