### ISSUE TITLE
Migrasi wajah BlankOn ke domain *.blankon.id

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#89]
Layanan yang terkait proyek distribusi Linux tetap berdomisili di *.boi.

Mohon dijabarkan domain/layanan mana saja yang akan dimigrasikan. cc @tuanpembual @samsulmaarif

**Comment by herpiko** [comment]
Yang sudah dikerjakan mohon untuk didaftarkan ke https://github.com/BlankOn/wiki/blob/master/TimPengembang/Infrastruktur/DomainDanLayanan.md

**Comment by samsulmaarif** [comment]
Mungkin ini beberapa yang saya usulkan untuk dimigrasikan domainnya pak:

- [ ] serambi.boi -> serambi.blankon.id
- [ ] www.boi -> www.blankon.id
- [ ] manokwari.boi -> manokwari.blankon.id
- [ ] sajadah.boi -> sajarah.blankon.id
- [ ] konf*.boi -> konf*.blankon.id
- [ ] panduan.boi -> panduan.blankon.id

Beberapa daftar dalam #60 yang tidak perlu dihidupkan lagi mungkin perlu kita coret.

**Comment by kudaliar032** [comment]
Pak @samsulmaarif, minta tolong untuk pointing domain berikut ke server rafi:

- [ ] sajadah.blankon.id

**Comment by samsulmaarif** [comment]
@kudaliar032 Done
