### ISSUE TITLE
Penggalangan dana

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#90]
BlankOn butuh biaya untuk pengembangan:
1. Bayar sewa colo
2. Promosi
3. Kegiatan
4. Domain
5. Dll

Perlu disiapkan juga format laporan keuangan yang disepakati.

**Comment by slamets75** [comment]
@herpiko Monitor

**Comment by herpiko** [comment]
Tiket ini saya tutup, duplikat dengan https://github.com/BlankOn/Verbeek/issues/114
