### ISSUE TITLE
Catatan Keuangan

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#91]
Sementara ditumpuk di sini sampai format catatan keuangan sudah ada/disepakati.

Dokumen kwitansi paling dekat yang bisa ditempel kemari:
- Perpanjangan blankon.id
- SSD 128GB untuk waljinah

**Comment by tuanpembual** [comment]
[Uploading Tokopedia-TeamSSD.pdf…]()
Kwitansi SSD

**Comment by tuanpembual** [comment]
[Tokopedia-TeamSSD.pdf](https://github.com/BlankOn/Verbeek/files/5481996/Tokopedia-TeamSSD.pdf)
Kwitansi SSD

**Comment by herpiko** [comment]
Usulan bentuk laporan:

- Format berkas PDF
- Ditandatangani dengan kunci GPG milik koordinator Humas
- Berkas diunggah ke https://github.com/BlankOn/wiki/tree/master/Assets/Others
- Daftar berkas dan tanda tangan digitalnya dirilis di wiki pada halaman (belom dibikin) https://github.com/BlankOn/wiki/tree/master/TimPengembang/Humas/LaporanKeuangan.md
- saweran.boi/donasi.boi dapat menautkan sesuatu di halamannya ke halaman di atas.
- Format isi dokumen:
--------------------------------------------------------
Tanggal laporan: 31 Januari 2021
Kas awal: Rp. 123.123.123
Kas akhir: Rp. 123.000.000 

### Pengeluaran

| Tanggal   |  Divisi  | Pengeluaran   |  Jumlah (Rp) |
|:---------|:-------------:|------|-----:|
|  3 Januari 2020  |  Infrastruktur | Sewa colocation/bandwith 1 tahun di XYZ  [0] |  123.000 |
| 22 Januari 2020 |  Humas  | Pencetakan kartu nama untuk Humas [1] |  123 |

### Lampiran

[0] Tempel foto kwitansi di sini.
[1] Tempel foto kwitansi di sini.

**Comment by tuanpembual** [comment]
done by this ticket, but still open ticket for invoce

https://docs.google.com/spreadsheets/d/1ku2HehcQCphvZv0HjNwD_J3V7Gj_Le8kvwpIOLFRonI/edit?pli=1#gid=0

**Comment by tuanpembual** [comment]
[Invoice-2901980.pdf](https://github.com/BlankOn/Verbeek/files/5653472/Invoice-2901980.pdf)

**Comment by samsulmaarif** [comment]
Catatan keuangan sudah ditampilkan di sini --> https://blankon.id/berita/2020/11/20/laporan-donasi-ke-proyek-blankon.html
