### ISSUE TITLE
Zsync belum bekerja dengan benar

### ISSUE THREAD

**Issue by herpiko** [BlankOn/Verbeek#93]
```
➜  iso zsync http://cdimage.blankonlinux.or.id/blankon/jahitan-harian/20201031-19/20201031-19-live-image-amd64.hybrid.iso.zsync
failed on url http://cdimage.blankonlinux.or.id/blankon/jahitan-harian/20201031-19/20201031-19-live-image-amd64.hybrid.iso.zsync
could not read control file from URL http://cdimage.blankonlinux.or.id/blankon/jahitan-harian/20201031-19/20201031-19-live-image-amd64.hybrid.iso.zsync
➜  is
```

**Comment by leonyonz** [comment]
Ini ngeceknya pakai perintah ini Pak @herpiko ? : 

`$ zsync https://cdimage.blankonlinux.or.id/blankon/jahitan-harian/20201125-12/20201125-12-live-image-amd64.hybrid.iso.zsync`

Kalo dicek masih failed perhari ini.

![image](https://user-images.githubusercontent.com/42370275/100141605-4706e000-2ec5-11eb-9aca-869a29efa81e.png)

**Comment by herpiko** [comment]
Salah cara ternyata di tiket, cobain ini, https://blog.kukuh.syafaat.id/2020/Mencoba-Jahitan-BlankOn-Verbeek/

**Comment by artemtech** [comment]
> 
> `$ zsync https://cdimage.blankonlinux.or.id/blankon/jahitan-harian/20201125-12/20201125-12-live-image-amd64.hybrid.iso.zsync`
> 
kalau diselidiki lewat raw file zsync ini, di bagian atas sendiri, dia mencari berkas live-image-amd64.hybrid.iso. Tapi karena ada [skrip pasca build image](https://github.com/BlankOn/blankon-live-build/blob/master/build.sh#L54-L59) yang mengubah nama image sehingga ada prefix tanggal di depannya, zsync tidak menemukan file itu.

**Comment by leonyonz** [comment]
Sedikit usulan, untuk penamaan berkas ISO jahitan harian bisa disesuaikan agar tidak menggunakan prefix tanggal, Jadi nantinya yang membedakan adalah direktori induknya saja.

Terima kasih.

### Referensi

http://cdimage.ubuntu.com/daily-live/

**Comment by samsulmaarif** [comment]
Terkait penamaan ini sebenarnya terkait dengan BlanKongkow tim JK dengan tim Infra beberapa waktu lalu (video: https://www.youtube.com/watch?v=BI45iC0Temw), penamaan saat ini dirasa OK untuk penggunaan jk.boi. 

Namun sebenarnya bisa disesuaikan dengan kebutuhan zsync, sedangkan untuk jk.boi bisa menyesuaikan di scrip unduhnya.

**Comment by herpiko** [comment]
Temuan (perlu diwikikan jadi semacam catatan/guide):

- [ ] Pake cache, cukup pake sudo lb clean setiap memulai build baru. Perbandingannya 10 menit dengan cache vs 30-60 menit tanpa cache
- [ ] Nilai URL di berkas *.zsync perlu diperbarui setiap selesai build
- [ ] Nama berkas diatur di config/common, jangan merename sendiri
- [ ] Semua field dengan string parent di config/bootstrap terkait dengan kebutuhan saat membangun ISO. Komponen repo untuk parent perlu diset hanya ke "main". Semua paket kebutuhan ISO bawa ke komponen "main", bukan yang lain.
- [ ] Penyuntikan kunci diletakan di  config/archives/live.key.binaries dan config/archives/live.key.chroot, bukan dengan paket deb di config/packages

Catetan penting:
- /mnt/blankon-live-build sekarang tidak lagi berbentuk direktori git, tidak ada hubungannya secara langsung dengan https://github.com/blankon/blankon-live-build dan bukan deployment. Ini hanya direktori kerja untuk worker

**Comment by herpiko** [comment]
@mdzulkifli @leonyonz silakan diuji kembali, ambil zsync-nya dari current.

![Screenshot from 2020-11-29 11-35-59](https://user-images.githubusercontent.com/2534060/100533461-24fbbd80-3237-11eb-993d-f4a94c46e550.png)

**Comment by leonyonz** [comment]
Noted Pak @herpiko

**Comment by leonyonz** [comment]
Hi Pak @herpiko terlampir hasil uji saya untuk jahitan current:

- **Proses Download**

![image](https://user-images.githubusercontent.com/42370275/100533540-4ad59200-3238-11eb-8315-e06b0dc5d9b3.png)

- **Proses Selesai**

![image](https://user-images.githubusercontent.com/42370275/100533604-e49d3f00-3238-11eb-96e7-007d8e7f87d3.png)

**Uji Jalankan Image**

![image](https://user-images.githubusercontent.com/42370275/100533661-64c3a480-3239-11eb-8c62-59013edf6c14.png)

**Comment by herpiko** [comment]
@leonyonz Kok yang muncul uluwatu ya. 😂

**Comment by leonyonz** [comment]
eh, kirain memang sengaja pake iso itu

![image](https://user-images.githubusercontent.com/42370275/100533985-229c6200-323d-11eb-90f5-d836737c3d9c.png)

**Comment by leonyonz** [comment]
Maaf salah ISO Pak hehehe 

- **Berikut terlampir hasil jalankan ISO jahitan 20201129-16**
![image](https://user-images.githubusercontent.com/42370275/100534033-7909a080-323d-11eb-93e3-1a97b1993272.png)
